import { Building2, CalendarDays, FileText, Landmark, ReceiptText, UsersRound } from "lucide-react";
import Link from "next/link";

import { CompaniesDirectory } from "@/components/companies-directory";
import { ContextSelector } from "@/components/context-selector";
import { MobileSearch } from "@/components/mobile-search";
import { NotificationMenu } from "@/components/notification-menu";
import { ThemeToggle } from "@/components/theme-toggle";
import { UserMenu } from "@/components/user-menu";

const nav = [{ label: "Resumen", href: "/", icon: Landmark }, { label: "Empresas", href: "/empresas", icon: Building2 }, { label: "Calendario", href: "/calendario", icon: CalendarDays }, { label: "Operaciones", href: "#", icon: ReceiptText }, { label: "Documentos", href: "#", icon: FileText }, { label: "Equipo", href: "#", icon: UsersRound }];
export default function CompaniesPage() { return <main className="min-h-screen bg-[#f7f7f4] text-stone-900 dark:bg-stone-950 dark:text-stone-100"><aside className="fixed inset-y-0 left-0 hidden w-64 flex-col border-r border-stone-200 bg-white px-4 py-5 dark:border-stone-800 dark:bg-stone-900 lg:flex"><div className="mb-10 flex items-center gap-3 px-2"><div className="grid size-9 place-items-center rounded-xl bg-[#14352d] text-sm font-bold text-white">PX</div><div><p className="font-semibold">proyectoxyz</p><p className="text-xs text-stone-500">Firma contable</p></div></div><nav className="space-y-1">{nav.map(({ label, href, icon: Icon }) => <Link className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm ${label === "Empresas" ? "bg-[#e7f0e9] font-medium text-[#14352d] dark:bg-emerald-950 dark:text-emerald-100" : "text-stone-600 hover:bg-stone-100 dark:text-stone-300 dark:hover:bg-stone-800"}`} href={href} key={label}><Icon size={18} />{label}</Link>)}</nav></aside><section className="lg:pl-64"><header className="sticky top-0 z-10 flex h-18 items-center justify-between border-b border-stone-200 bg-[#f7f7f4]/90 px-3 backdrop-blur dark:border-stone-800 dark:bg-stone-950/90 sm:px-5 lg:px-10"><div className="flex items-center gap-2"><Link className="grid size-9 place-items-center rounded-xl bg-[#14352d] text-sm font-bold text-white lg:hidden" href="/">PX</Link><ContextSelector mobile /><MobileSearch /><ContextSelector /></div><div className="flex items-center gap-1 sm:gap-3"><NotificationMenu /><div className="hidden sm:block"><ThemeToggle /></div><UserMenu /></div></header><CompaniesDirectory /></section></main>; }
