"use client";

import { AlertTriangle, Banknote, CalendarDays, Check, FileCheck2, Landmark, Plus, Save, Utensils, WalletCards } from "lucide-react";
import { useState, type ComponentType, type ReactNode } from "react";

import { AttachmentInput } from "@/components/ui/attachment-input";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { SimpleSelect } from "@/components/ui/simple-select";

type Deduction = { id: number; name: string; rate: string; base: string; cap: string; effective: string; source: string };
const authorizedPeople = [
  { id: "rrhh", name: "María Fernanda Rojas", role: "Gerente de Recursos Humanos" },
  { id: "gerencia", name: "Carlos Enrique Medina", role: "Gerente general" },
  { id: "administracion", name: "Daniela Suárez", role: "Gerente de Administración" },
];

export function CompanyLaborSettings() {
  const [frequency, setFrequency] = useState("Quincenal");
  const [currency, setCurrency] = useState("USD");
  const [rateMode, setRateMode] = useState("propia");
  const [benefitRegime, setBenefitRegime] = useState("base");
  const [foodCadence, setFoodCadence] = useState("Quincenal");
  const [saved, setSaved] = useState(false);
  const [signature, setSignature] = useState("");
  const [authorizedSignerId, setAuthorizedSignerId] = useState("rrhh");
  const [deductions, setDeductions] = useState<Deduction[]>([
    { id: 1, name: "Seguro social · IVSS", rate: "", base: "Pendiente de definir", cap: "", effective: "", source: "" },
    { id: 2, name: "FAOV", rate: "", base: "Pendiente de definir", cap: "", effective: "", source: "" },
  ]);
  const updateDeduction = (id: number, key: keyof Deduction, value: string) => setDeductions((current) => current.map((item) => item.id === id ? { ...item, [key]: value } : item));
  const authorizedSigner = authorizedPeople.find((person) => person.id === authorizedSignerId) ?? authorizedPeople[0];
  return (
    <div className="mx-auto w-full min-w-0 py-7 pb-16"><header className="flex min-w-0 flex-col gap-4 border-b border-stone-200 pb-6 dark:border-stone-800 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm text-stone-500">Empresa activa / Configuración / Laboral</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Configuración laboral</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-stone-600 dark:text-stone-300">Frecuencia de nómina, conversión a bolívares, beneficios y deducciones propias de Distribuidora El Roble, C.A.</p></div><Button className="h-9 bg-[#14352d] hover:bg-[#0e2821]" onClick={() => setSaved(true)}><Save /> Guardar borrador</Button></header>
      {saved && <p className="mt-5 flex items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950/25 dark:text-emerald-200"><Check size={16} /> Cambios guardados en esta vista demostrativa. Las reglas incompletas no se consideran activas.</p>}
      <div className="mt-6 grid gap-6 xl:grid-cols-[14rem_minmax(0,1fr)]"><aside className="hidden h-fit rounded-xl border border-stone-200 bg-white p-3 shadow-sm dark:border-stone-800 dark:bg-stone-900 xl:block"><p className="px-2 pb-2 text-xs font-semibold uppercase tracking-wide text-stone-400">Configuración laboral</p>{[["nomina", "Nómina y moneda"], ["salario-minimo", "Salario mínimo"], ["beneficios", "Beneficios"], ["alimentacion", "Alimentación"], ["deducciones", "Deducciones"], ["documentos", "Firma autorizada"]].map(([id, label]) => <a className="block rounded-lg px-2 py-2 text-sm text-stone-600 hover:bg-stone-100 hover:text-[#14352d] dark:text-stone-300 dark:hover:bg-stone-800" href={`#${id}`} key={id}>{label}</a>)}</aside><main className="min-w-0 space-y-6">
        <SettingCard icon={WalletCards} id="nomina" title="Nómina y moneda de referencia" text="La empresa define cómo acuerda salarios; todos los recibos se emiten en bolívares."><div className="grid gap-4 md:grid-cols-2"><Field label="Frecuencia de nómina"><SimpleSelect className="field mt-1.5" onChange={(event) => setFrequency(event.target.value)} value={frequency}><option>Quincenal</option><option>Mensual</option></SimpleSelect></Field><Field label="Divisa del salario acordado"><SimpleSelect className="field mt-1.5" onChange={(event) => setCurrency(event.target.value)} value={currency}><option>USD</option><option>EUR</option></SimpleSelect></Field><Field label="Fuente de conversión"><SimpleSelect className="field mt-1.5" onChange={(event) => setRateMode(event.target.value)} value={rateMode}><option value="bcv">Tasa BCV de la divisa seleccionada</option><option value="propia">Tasa propia de la empresa</option></SimpleSelect></Field><Field label="Momento de fijación"><SimpleSelect className="field mt-1.5"><option>Al crear cada nómina</option><option>Fecha de pago</option></SimpleSelect></Field></div>{rateMode === "propia" && <div className="mt-4 rounded-lg border border-sky-200 bg-sky-50 p-4 text-sm text-sky-950 dark:border-sky-900 dark:bg-sky-950/25 dark:text-sky-100"><b>Tasa manual obligatoria.</b><p className="mt-1 leading-5">Cada nómina solicitará tasa, fecha y nota de autorización para conservar trazabilidad.</p></div>}<p className="mt-4 text-xs leading-5 text-stone-500">Configuración actual: {frequency.toLowerCase()}, salario acordado en {currency} y conversión mediante {rateMode === "propia" ? "tasa propia" : "tasa BCV"}.</p></SettingCard>
        <SettingCard icon={Landmark} id="salario-minimo" title="Salario mínimo de referencia" text="Información general del sistema; no crea un segundo salario por trabajador."><div className="grid gap-4 md:grid-cols-2"><Field label="Monto vigente · Bs"><Input className="field mt-1.5" inputMode="decimal" placeholder="Ingrese el monto validado" /></Field><Field label="Vigente desde"><Input className="field mt-1.5" type="date" /></Field><Field wide label="Fuente oficial"><Input className="field mt-1.5" placeholder="Gaceta, decreto o enlace validado" /></Field></div><p className="mt-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs leading-5 text-amber-900 dark:border-amber-900 dark:bg-amber-950/25 dark:text-amber-100"><AlertTriangle className="mr-1 inline" size={14} />No se precarga un monto como vigente sin fuente y fecha de aplicación.</p></SettingCard>
        <SettingCard icon={CalendarDays} id="beneficios" title="Vacaciones y utilidades" text="La regla base puede conservarse o sustituirse por beneficios superiores definidos por la empresa."><div className="grid gap-4 md:grid-cols-2"><Field label="Esquema de beneficios"><SimpleSelect className="field mt-1.5" onChange={(event) => setBenefitRegime(event.target.value)} value={benefitRegime}><option value="base">Según regla base configurada</option><option value="especial">Beneficios personalizados</option></SimpleSelect></Field><Field label="Programación del disfrute"><SimpleSelect className="field mt-1.5"><option>Al cumplir el aniversario</option><option>Política colectiva de fin de año</option></SimpleSelect></Field></div><div className="mt-5 grid gap-4 lg:grid-cols-3"><BenefitRule title="Vacaciones" base="15" increment="1" cap="30" editable={benefitRegime === "especial"} /><BenefitRule title="Bono vacacional" base="15" increment="1" cap="30" editable={benefitRegime === "especial"} /><BenefitRule title="Utilidades" base="30" increment="0" cap="" editable={benefitRegime === "especial"} /></div><div className="mt-5 grid gap-4 md:grid-cols-3"><Field label="Base · vacaciones"><SimpleSelect className="field mt-1.5"><option>Salario acordado vigente</option><option>Salario mínimo</option><option>Por definir</option></SimpleSelect></Field><Field label="Base · bono vacacional"><SimpleSelect className="field mt-1.5"><option>Por definir</option><option>Salario acordado vigente</option><option>Salario mínimo</option></SimpleSelect></Field><Field label="Base · utilidades"><SimpleSelect className="field mt-1.5"><option>Por definir</option><option>Salario acordado vigente</option><option>Promedio del período</option></SimpleSelect></Field></div><p className="mt-4 text-xs leading-5 text-stone-500">Cada concepto conserva su propia base. Las opciones marcadas “Por definir” no producirán un cálculo definitivo.</p></SettingCard>
        <SettingCard icon={Utensils} id="alimentacion" title="Bono de alimentación" text="Monto mensual de referencia que puede mejorarse individualmente por trabajador."><div className="grid gap-4 md:grid-cols-3"><Field label="Monto mínimo mensual"><Input className="field mt-1.5" defaultValue="40" inputMode="decimal" /></Field><Field label="Moneda"><SimpleSelect className="field mt-1.5"><option>USD</option></SimpleSelect></Field><Field label="Entrega en nómina"><SimpleSelect className="field mt-1.5" onChange={(event) => setFoodCadence(event.target.value)} value={foodCadence}><option>Quincenal</option><option>Mensual</option></SimpleSelect></Field><Field wide label="Fuente y vigencia"><Input className="field mt-1.5" placeholder="Documento validado y fecha de aplicación" /></Field></div><div className="mt-4 rounded-lg bg-stone-50 p-4 text-sm leading-6 text-stone-600 dark:bg-stone-800 dark:text-stone-300"><b>Aplicación:</b> el monto es total mensual. Si la nómina es quincenal, se divide entre ambas quincenas. Las inasistencias no lo disminuyen y cada ficha puede guardar un monto superior.</div></SettingCard>
        <SettingCard icon={Banknote} id="deducciones" title="Deducciones y aportes" text="Cada parámetro requiere porcentaje, base, vigencia y fuente antes de activarse."><div className="space-y-4">{deductions.map((item) => <section className="rounded-xl border border-stone-200 p-4 dark:border-stone-700" key={item.id}><div className="flex items-center justify-between"><h3 className="font-semibold">{item.name}</h3><span className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-medium text-amber-700">Pendiente</span></div><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Field label="Porcentaje"><Input className="field mt-1.5" inputMode="decimal" onChange={(event) => updateDeduction(item.id, "rate", event.target.value)} placeholder="Definir" value={item.rate} /></Field><Field label="Base de cálculo"><SimpleSelect className="field mt-1.5" onChange={(event) => updateDeduction(item.id, "base", event.target.value)} value={item.base}><option>Pendiente de definir</option><option>Salario mínimo</option><option>Salario acordado convertido</option><option>Base personalizada</option></SimpleSelect></Field><Field label="Tope"><Input className="field mt-1.5" onChange={(event) => updateDeduction(item.id, "cap", event.target.value)} placeholder="Si aplica" value={item.cap} /></Field><Field label="Vigente desde"><Input className="field mt-1.5" onChange={(event) => updateDeduction(item.id, "effective", event.target.value)} type="date" value={item.effective} /></Field><Field wide label="Fuente"><Input className="field mt-1.5" onChange={(event) => updateDeduction(item.id, "source", event.target.value)} placeholder="Norma o documento validado" value={item.source} /></Field></div></section>)}</div><Button className="mt-4" onClick={() => setDeductions((current) => [...current, { id: Date.now(), name: "Nueva deducción", rate: "", base: "Pendiente de definir", cap: "", effective: "", source: "" }])} variant="outline"><Plus /> Agregar deducción</Button></SettingCard>
        <SettingCard icon={FileCheck2} id="documentos" title="Firma autorizada" text="Selecciona quién firma los recibos de nómina y beneficios en representación de la empresa."><div className="grid gap-4 md:grid-cols-2"><Field label="Personal autorizado"><SimpleSelect className="field mt-1.5" onChange={(event) => setAuthorizedSignerId(event.target.value)} value={authorizedSignerId}>{authorizedPeople.map((person) => <option key={person.id} value={person.id}>{person.name}</option>)}</SimpleSelect></Field><div className="rounded-lg bg-stone-50 p-4 dark:bg-stone-800"><p className="text-xs font-medium uppercase tracking-wide text-stone-400">Datos que saldrán en el recibo</p><p className="mt-2 font-semibold">{authorizedSigner.name}</p><p className="mt-1 text-sm text-stone-500">{authorizedSigner.role}</p></div></div><label className="mt-4 flex cursor-pointer items-center gap-3 rounded-lg border border-dashed border-stone-300 p-4 hover:bg-stone-50 dark:border-stone-700 dark:hover:bg-stone-800"><FileCheck2 className="text-[#14352d] dark:text-emerald-300" size={20} /><span className="min-w-0 flex-1"><b className="block text-sm">Firma de {authorizedSigner.name}</b><span className="mt-1 block truncate text-xs text-stone-500">{signature || "Seleccionar imagen PNG o JPG"}</span></span><AttachmentInput accept="image/png,image/jpeg" className="sr-only" onChange={(event) => setSignature(event.target.files?.[0]?.name ?? "")} /></label><p className="mt-4 text-xs leading-5 text-stone-500">El logo y el sello se administran desde Información general de la empresa. La firma debe conservarse cifrada, con acceso por empresa y registro de auditoría.</p></SettingCard>
      </main></div>
    </div>
  );
}

function BenefitRule({ title, base, increment, cap, editable }: { title: string; base: string; increment: string; cap: string; editable: boolean }) { return <section className="rounded-xl border border-stone-200 p-4 dark:border-stone-700"><h3 className="font-semibold">{title}</h3><div className="mt-3 grid grid-cols-3 gap-2"><MiniField disabled={!editable} label="Base" value={base} /><MiniField disabled={!editable} label="+ por año" value={increment} /><MiniField disabled={!editable} label="Tope" value={cap} /></div><p className="mt-3 text-xs text-stone-500">Valores en días · {editable ? "personalizable" : "regla base"}</p></section>; }
function MiniField({ label, value, disabled }: { label: string; value: string; disabled: boolean }) { return <label className="text-[11px] font-medium text-stone-500">{label}<Input className="field mt-1 h-8 px-2" defaultValue={value} disabled={disabled} inputMode="numeric" /></label>; }
function SettingCard({ children, icon: Icon, id, text, title }: { children: ReactNode; icon: ComponentType<{ size?: number }>; id: string; text: string; title: string }) { return <section className="scroll-mt-24 rounded-xl border border-stone-200 bg-white shadow-sm dark:border-stone-800 dark:bg-stone-900" id={id}><header className="flex gap-3 border-b border-stone-100 p-5 dark:border-stone-800"><span className="grid size-9 shrink-0 place-items-center rounded-lg bg-[#e7f0e9] text-[#14352d] dark:bg-emerald-950 dark:text-emerald-200"><Icon size={18} /></span><div><h2 className="font-semibold">{title}</h2><p className="mt-1 text-sm leading-5 text-stone-500">{text}</p></div></header><div className="p-5">{children}</div></section>; }
function Field({ children, label, wide = false }: { children: ReactNode; label: string; wide?: boolean }) { return <label className={`text-sm font-medium ${wide ? "md:col-span-2 xl:col-span-3" : ""}`}>{label}{children}</label>; }
