"use client";

import { AttachmentInput } from "@/components/ui/attachment-input";
import { AlertTriangle, Building2, CalendarClock, Check, FileText, Landmark, Pencil, Plus, Save, Settings2, Trash2, UsersRound } from "lucide-react";
import Link from "next/link";
import { useState, type ComponentType, type ReactNode } from "react";

import { DatePicker } from "@/components/ui/date-picker";
import { Input } from "@/components/ui/input";
import { SimpleSelect } from "@/components/ui/simple-select";
import { firmServiceOfferings, firmTaxOfferings, type FirmOffering } from "@/lib/firm-offerings";

type Item = { id: number; title: string; detail: string };
type Mode = "branch" | "board";
const field = "field mt-1.5";

export function CompanyEditor() {
  const [taxpayerType, setTaxpayerType] = useState("Ordinario");
  const [selectedTaxes, setSelectedTaxes] = useState(() => new Set(["iva", "municipal", "inces"]));
  const [selectedServices, setSelectedServices] = useState(() => new Set(["electricidad", "agua"]));
  const [branches, setBranches] = useState<Item[]>([
    { id: 1, title: "Casa matriz", detail: "Av. Principal, local 4 · Municipio principal" },
    { id: 2, title: "Sucursal Centro", detail: "Centro comercial, nivel 1 · Municipio de la sucursal" },
  ]);
  const [board, setBoard] = useState<Item[]>([{ id: 1, title: "Presidente · María Rojas", detail: "Vigente hasta 10 may 2028" }]);
  const [mode, setMode] = useState<Mode | null>(null);
  const [editing, setEditing] = useState<Item | null>(null);
  const [title, setTitle] = useState("");
  const [detail, setDetail] = useState("");
  const [saved, setSaved] = useState(false);
  const [deleteOpen, setDeleteOpen] = useState(false);
  const [deleteText, setDeleteText] = useState("");
  const [deleted, setDeleted] = useState(false);
  const [incesSeal, setIncesSeal] = useState<string | null>(null);
  const [incesSignature, setIncesSignature] = useState<string | null>(null);
  const [companyLogo, setCompanyLogo] = useState<string | null>(null);
  const [companySeal, setCompanySeal] = useState<string | null>(null);

  const toggle = (id: string, type: "tax" | "service") => {
    const setter = type === "tax" ? setSelectedTaxes : setSelectedServices;
    setter((current) => { const next = new Set(current); next.has(id) ? next.delete(id) : next.add(id); return next; });
    setSaved(false);
  };

  function openItem(nextMode: Mode, item?: Item) {
    setMode(nextMode); setEditing(item ?? null); setTitle(item?.title ?? ""); setDetail(item?.detail ?? "");
  }

  function saveItem() {
    if (!mode || !title.trim() || !detail.trim()) return;
    const apply = (items: Item[]) => editing ? items.map((item) => item.id === editing.id ? { ...item, title, detail } : item) : [...items, { id: Date.now(), title, detail }];
    mode === "branch" ? setBranches(apply) : setBoard(apply);
    setMode(null);
  }

  const selectedCount = selectedTaxes.size + selectedServices.size;
  return <div className="mx-auto w-full min-w-0 py-7 pb-16"><header className="flex min-w-0 flex-col gap-4 border-b border-stone-200 pb-6 dark:border-stone-800 lg:flex-row lg:items-end lg:justify-between"><div className="min-w-0"><p className="text-sm text-stone-500">Empresa activa / Configuración</p><div className="mt-2 flex flex-wrap items-center gap-3"><h1 className="break-words text-3xl font-semibold tracking-tight sm:text-4xl">Nueva Confitería del Sur, C.A.</h1><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-medium text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300">Activa</span></div><p className="mt-2 max-w-3xl text-sm leading-6 text-stone-600 dark:text-stone-300">Identidad, cobertura contratada, parámetros propios, estructura legal y accesos de la empresa.</p></div><button className="inline-flex h-9 shrink-0 items-center justify-center gap-2 rounded-lg bg-[#14352d] px-3 text-sm font-medium text-white" onClick={() => setSaved(true)} type="button"><Save size={16} /> Guardar cambios</button></header>

    <div className="mt-6 grid gap-4 sm:grid-cols-3"><Summary label="Plan asignado" value="Integral" detail="Cobertura personalizable" /><Summary label="Cobertura activa" value={`${selectedCount} elementos`} detail={`${selectedTaxes.size} obligaciones · ${selectedServices.size} servicios`} /><Summary label="Régimen" value={taxpayerType} detail="Determina calendario y periodicidad" /></div>

    <div className="mt-6 grid gap-6 xl:grid-cols-[14rem_minmax(0,1fr)]"><aside className="hidden h-fit max-h-[calc(100vh-6rem)] overflow-y-auto rounded-xl border border-stone-200 bg-white p-3 shadow-sm dark:border-stone-800 dark:bg-stone-900 xl:sticky xl:top-20 xl:block xl:self-start"><p className="px-2 pb-2 text-xs font-semibold uppercase tracking-wide text-stone-400">Ficha de empresa</p>{[["general", "Información general"], ["cobertura", "Cobertura"], ...(selectedTaxes.has("municipal") ? [["municipal", "Impuesto municipal"]] : []), ["sucursales", "Sucursales"], ["legal", "Información legal"], ...(selectedTaxes.has("inces") ? [["inces", "INCES"]] : []), ["accesos", "Portal del cliente"], ["eliminar", "Eliminar empresa"]].map(([id, label]) => <a className="block rounded-lg px-2 py-2 text-sm text-stone-600 hover:bg-stone-100 hover:text-[#14352d] dark:text-stone-300 dark:hover:bg-stone-800" href={`#${id}`} key={id}>{label}</a>)}</aside>

      <main className="min-w-0 space-y-6"><Card id="general" icon={Building2} title="Información general" text="Identificación fiscal, responsable, logo y sello propios de la empresa."><div className="grid gap-4 md:grid-cols-2"><Field label="Razón social"><Input className={field} defaultValue="Nueva Confitería del Sur, C.A." /></Field><Field label="RIF"><Input className={field} defaultValue="J-309951441" /></Field><Field label="Domicilio fiscal"><Input className={field} defaultValue="Av. Principal, local 4" /></Field><Field label="Correo"><Input className={field} defaultValue="administracion@nuevaconfiteria.com" /></Field><Field label="Tipo de contribuyente"><SimpleSelect className={field} onChange={(event) => setTaxpayerType(event.target.value)} value={taxpayerType}><option>Ordinario</option><option>Formal</option><option>Sujeto pasivo especial</option></SimpleSelect></Field><Field label="Contador responsable"><SimpleSelect className={field}><option>María Pérez</option><option>Luis Suárez</option></SimpleSelect></Field><Field label="Número patronal · IVSS"><Input className={field} defaultValue="123456789" inputMode="numeric" /></Field><Field label="N.º de afiliación · FAOV"><Input className={field} defaultValue="0321085357530000000" inputMode="numeric" /></Field></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><UploadField label="Logo de la empresa" value={companyLogo ?? "PNG, JPG o SVG"} onChange={setCompanyLogo} /><UploadField label="Sello de la empresa" value={companySeal ?? "PNG o imagen del sello"} onChange={setCompanySeal} /></div><p className="mt-3 text-xs leading-5 text-stone-500">El logo y el sello se reutilizarán en contratos y recibos emitidos para esta empresa.</p>{taxpayerType === "Sujeto pasivo especial" && <div className="mt-5 rounded-xl border border-violet-200 bg-violet-50/60 p-4 text-sm text-violet-950 dark:border-violet-900 dark:bg-violet-950/25 dark:text-violet-100"><p className="flex items-center gap-2 font-semibold"><CalendarClock size={17} /> Régimen SPE activo</p><p className="mt-1 leading-5">Las obligaciones SPE seleccionadas usarán su periodicidad especial y la fecha del calendario anual correspondiente al terminal del RIF.</p><Link className="mt-3 inline-block font-medium text-violet-700 hover:underline dark:text-violet-300" href="/configuracion/impuestos#calendario-spe">Consultar calendario de la firma</Link></div>}</Card>

        <Card id="cobertura" icon={Settings2} title="Declaraciones y servicios" text="Selecciona únicamente entre las obligaciones y servicios que la firma mantiene disponibles."><div className="rounded-xl border border-sky-200 bg-sky-50/70 p-4 text-sm leading-6 text-sky-950 dark:border-sky-900 dark:bg-sky-950/25 dark:text-sky-100"><b>La empresa no crea reglas fiscales.</b> Esta selección hereda periodicidad, vencimiento y fuente desde la configuración de la firma; aquí solo se define qué le aplica.</div><OfferingSection actionHref="/configuracion/impuestos" actionLabel="Administrar impuestos de la firma" items={firmTaxOfferings} onToggle={(id) => toggle(id, "tax")} selected={selectedTaxes} title="Obligaciones tributarias" /><OfferingSection actionHref="/configuracion/servicios" actionLabel="Administrar servicios de la firma" items={firmServiceOfferings} onToggle={(id) => toggle(id, "service")} selected={selectedServices} title="Servicios" /><p className="mt-5 text-xs leading-5 text-stone-500">Catálogo demostrativo compartido en esta interfaz. La sincronización definitiva se realizará desde la persistencia de la firma.</p></Card>

        {selectedTaxes.has("municipal") && <MunicipalConfiguration />}

        <Card id="sucursales" icon={Building2} title="Sucursales y jurisdicciones" text="Cada sede conserva su domicilio y alcaldía aplicable."><EditableList rows={branches} onAdd={() => openItem("branch")} onEdit={(item) => openItem("branch", item)} onDelete={(id) => setBranches((items) => items.filter((item) => item.id !== id))} /></Card>

        <Card id="legal" icon={FileText} title="Información legal y junta directiva" text="Datos registrales, capital y cargos con sus fechas de vigencia."><div className="grid gap-4 md:grid-cols-3"><Field label="Fecha de constitución"><DatePicker className={field} /></Field><Field label="Registro mercantil"><Input className={field} /></Field><Field label="Folio"><Input className={field} /></Field><Field label="Documento / tomo"><Input className={field} /></Field><Field label="Capital social vigente"><Input className={field} /></Field></div><p className="mt-5 font-semibold">Junta directiva</p><EditableList rows={board} onAdd={() => openItem("board")} onEdit={(item) => openItem("board", item)} onDelete={(id) => setBoard((items) => items.filter((item) => item.id !== id))} /></Card>

        {selectedTaxes.has("inces") && <IncesConfiguration incesSeal={incesSeal} incesSignature={incesSignature} setIncesSeal={setIncesSeal} setIncesSignature={setIncesSignature} />}

        <Card id="accesos" icon={UsersRound} title="Portal del cliente" text="Personas autorizadas para consultar y descargar documentos de esta empresa."><div className="rounded-lg border border-stone-200 p-4 dark:border-stone-700"><b>María Rojas</b><p className="mt-0.5 text-sm text-stone-500">Cliente administrador · Activo</p><div className="mt-3 flex gap-3"><button className="text-sm font-medium text-[#14352d]" type="button">Editar acceso</button><button className="text-sm font-medium text-rose-700" type="button">Revocar</button></div></div><button className="mt-4 inline-flex items-center gap-1 text-sm font-medium text-[#14352d]" type="button"><Plus size={16} /> Agregar usuario</button></Card>

        <Card id="eliminar" icon={Trash2} title="Eliminar empresa" text="Acción definitiva que exige confirmación explícita."><div className="rounded-lg border border-rose-200 bg-rose-50 p-4 text-sm leading-6 text-rose-900 dark:border-rose-900 dark:bg-rose-950/25 dark:text-rose-100"><AlertTriangle className="mr-2 inline" size={16} />Para eliminar la empresa se debe escribir <b>ELIMINAR</b>. Se eliminarán sus datos, documentos, declaraciones y evidencias.</div><button className="mt-4 rounded-lg border border-rose-300 px-3 py-2 text-sm font-medium text-rose-800 dark:text-rose-300" onClick={() => setDeleteOpen(true)} type="button">Eliminar definitivamente</button></Card>
        {saved && <p className="flex items-center gap-2 text-sm font-medium text-emerald-700 dark:text-emerald-300"><Check size={16} /> Cambios guardados en esta vista.</p>}{deleted && <p className="text-sm font-medium text-rose-700">Empresa marcada como eliminada en esta vista.</p>}</main></div>

    {deleteOpen && <Modal><h2 className="text-lg font-semibold text-rose-800 dark:text-rose-300">Eliminar Nueva Confitería del Sur, C.A.</h2><p className="mt-3 text-sm leading-6 text-stone-600 dark:text-stone-300">Esta acción eliminará definitivamente todos los datos y registros de la empresa.</p><Field label="Escribe ELIMINAR para confirmar"><Input className={field} onChange={(event) => setDeleteText(event.target.value)} value={deleteText} /></Field><div className="mt-6 flex justify-end gap-2"><button onClick={() => { setDeleteOpen(false); setDeleteText(""); }} type="button">Cancelar</button><button className="rounded-lg bg-rose-700 px-3 py-2 text-sm text-white disabled:cursor-not-allowed disabled:opacity-40" disabled={deleteText !== "ELIMINAR"} onClick={() => { setDeleted(true); setDeleteOpen(false); setDeleteText(""); }} type="button">Eliminar empresa</button></div></Modal>}
    {mode && <Modal><h2 className="text-lg font-semibold">{editing ? "Editar" : "Agregar"} {mode === "branch" ? "sucursal" : "cargo directivo"}</h2><Field label={mode === "branch" ? "Nombre de sucursal" : "Cargo y persona"}><Input className={field} onChange={(event) => setTitle(event.target.value)} value={title} /></Field><Field label={mode === "branch" ? "Domicilio y alcaldía" : "Fechas de vigencia"}><Input className={field} onChange={(event) => setDetail(event.target.value)} value={detail} /></Field><div className="mt-6 flex justify-end gap-2"><button onClick={() => setMode(null)} type="button">Cancelar</button><button className="rounded-lg bg-[#14352d] px-3 py-2 text-sm text-white" onClick={saveItem} type="button">Guardar</button></div></Modal>}
  </div>;
}

function OfferingSection({ actionHref, actionLabel, items, onToggle, selected, title }: { actionHref: string; actionLabel: string; items: FirmOffering[]; onToggle: (id: string) => void; selected: Set<string>; title: string }) {
  return <section className="mt-6"><div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-semibold">{title}</h3><p className="mt-1 text-xs text-stone-500">{selected.size} de {items.length} seleccionados</p></div><Link className="text-xs font-medium text-[#14352d] hover:underline dark:text-emerald-300" href={actionHref}>{actionLabel}</Link></div><div className="mt-3 grid gap-3 md:grid-cols-2">{items.map((item) => { const active = selected.has(item.id); return <button aria-pressed={active} className={`flex items-start gap-3 rounded-xl border p-4 text-left transition ${active ? "border-emerald-300 bg-emerald-50/70 dark:border-emerald-900 dark:bg-emerald-950/30" : "border-stone-200 hover:bg-stone-50 dark:border-stone-700 dark:hover:bg-stone-800"}`} key={item.id} onClick={() => onToggle(item.id)} type="button"><span className={`mt-0.5 grid size-5 shrink-0 place-items-center rounded-md border ${active ? "border-[#14352d] bg-[#14352d] text-white" : "border-stone-300 dark:border-stone-600"}`}>{active && <Check size={13} />}</span><span className="min-w-0"><b className="block text-sm">{item.name}</b><span className="mt-1 block text-xs leading-5 text-stone-500">{item.organism} · {item.cadence}</span></span></button>; })}</div></section>;
}

function MunicipalConfiguration() {
  return <Card id="municipal" icon={Landmark} title="Impuesto municipal" text="Parámetros particulares por sucursal y actividad económica; la regla general de vencimiento permanece en la firma."><div className="grid gap-4 md:grid-cols-2"><Field label="Sucursal"><SimpleSelect className={field}><option>Casa matriz</option><option>Sucursal Centro</option></SimpleSelect></Field><Field label="Alcaldía / jurisdicción"><Input className={field} defaultValue="Municipio principal" /></Field></div><div className="mt-5 overflow-hidden rounded-xl border border-stone-200 dark:border-stone-700"><div className="border-b border-stone-100 bg-stone-50 px-4 py-3 dark:border-stone-700 dark:bg-stone-800/60"><h3 className="text-sm font-semibold">Factores por actividad económica</h3><p className="mt-1 text-xs text-stone-500">Cada factor conserva su actividad, fuente municipal y vigencia.</p></div><div className="grid gap-4 p-4 lg:grid-cols-[minmax(0,1.5fr)_8rem_10rem_minmax(0,1fr)]"><Field label="Actividad económica"><Input className={field} defaultValue="Comercio al detal" /></Field><Field label="Factor (%)"><Input className={field} defaultValue="0,80" inputMode="decimal" /></Field><Field label="Aplicar desde"><DatePicker className={field} /></Field><Field label="Ordenanza o fuente"><Input className={field} placeholder="Documento municipal validado" /></Field></div><div className="border-t border-stone-100 px-4 py-3 dark:border-stone-700"><button className="inline-flex items-center gap-1 text-sm font-medium text-[#14352d] dark:text-emerald-300" type="button"><Plus size={15} /> Agregar actividad económica</button></div></div><p className="mt-4 text-xs leading-5 text-stone-500">La alícuota general de IVA no se configura aquí. Se hereda de Impuestos de la firma según su vigencia.</p></Card>;
}

function IncesConfiguration({ incesSeal, incesSignature, setIncesSeal, setIncesSignature }: { incesSeal: string | null; incesSignature: string | null; setIncesSeal: (value: string | null) => void; setIncesSignature: (value: string | null) => void }) {
  return <Card id="inces" icon={Landmark} title="INCES · configuración particular" text="Esta sección aparece porque INCES está seleccionado para la empresa."><div className="grid gap-4 md:grid-cols-2"><Field label="N.º de RNCP"><Input className={field} defaultValue="R-25-9-17-0087797" /></Field><Field label="Nombre del representante legal"><Input className={field} defaultValue="Suhail Al Hagari Abou" /></Field><Field label="Cédula del representante"><Input className={field} defaultValue="V-19.098.567" /></Field><Field label="Teléfono"><Input className={field} defaultValue="0414-6074156" /></Field><Field label="Correo"><Input className={field} defaultValue="administracion@nuevaconfiteria.com" type="email" /></Field></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><UploadField label="Sello digital" value={incesSeal ?? "PNG o imagen del sello"} onChange={setIncesSeal} /><UploadField label="Firma digital" value={incesSignature ?? "PNG o imagen de la firma"} onChange={setIncesSignature} /></div><p className="mt-4 text-xs leading-5 text-stone-500">Los archivos deberán almacenarse cifrados, con permisos por empresa y registro de auditoría al conectar la persistencia.</p></Card>;
}

function UploadField({ label, onChange, value }: { label: string; onChange: (value: string | null) => void; value: string }) {
  return <label className="flex cursor-pointer items-center gap-3 rounded-lg border border-dashed border-stone-300 p-3 hover:bg-stone-50 dark:border-stone-700 dark:hover:bg-stone-800"><FileText className="text-stone-500" size={18} /><span className="min-w-0 flex-1"><span className="block text-sm font-medium">{label}</span><span className="block truncate text-xs text-stone-500">{value}</span></span><AttachmentInput accept="image/*" className="sr-only" onChange={(event) => onChange(event.target.files?.[0]?.name ?? null)} /></label>;
}

function Summary({ detail, label, value }: { detail: string; label: string; value: string }) { return <div className="rounded-xl border border-stone-200 bg-white p-4 shadow-sm dark:border-stone-800 dark:bg-stone-900"><p className="text-xs font-medium uppercase tracking-wide text-stone-400">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p><p className="mt-1 text-xs text-stone-500">{detail}</p></div>; }
function Modal({ children }: { children: ReactNode }) { return <div aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-stone-950/40 p-4" role="dialog"><section className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl dark:bg-stone-900">{children}</section></div>; }
function Card({ children, icon: Icon, id, text, title }: { children: ReactNode; icon: ComponentType<{ size?: number }>; id: string; text: string; title: string }) { return <section className="scroll-mt-24 rounded-xl border border-stone-200 bg-white shadow-sm dark:border-stone-800 dark:bg-stone-900" id={id}><div className="flex gap-3 border-b border-stone-100 p-5 dark:border-stone-800"><div className="grid size-9 shrink-0 place-items-center rounded-lg bg-[#e7f0e9] text-[#14352d] dark:bg-emerald-950 dark:text-emerald-200"><Icon size={18} /></div><div><h2 className="font-semibold">{title}</h2><p className="mt-1 text-sm leading-5 text-stone-500">{text}</p></div></div><div className="p-5">{children}</div></section>; }
function Field({ children, label }: { children: ReactNode; label: string }) { return <label className="text-sm font-medium">{label}{children}</label>; }
function EditableList({ onAdd, onDelete, onEdit, rows }: { onAdd: () => void; onDelete: (id: number) => void; onEdit: (item: Item) => void; rows: Item[] }) { return <div className="mt-3 space-y-2">{rows.map((item) => <div className="flex items-center justify-between gap-3 rounded-lg border border-stone-200 p-3 dark:border-stone-700" key={item.id}><div className="min-w-0"><b>{item.title}</b><p className="mt-0.5 text-sm text-stone-500">{item.detail}</p></div><div className="flex shrink-0 gap-2"><button aria-label={`Editar ${item.title}`} onClick={() => onEdit(item)} type="button"><Pencil size={16} /></button><button aria-label={`Eliminar ${item.title}`} className="text-rose-600" onClick={() => onDelete(item.id)} type="button"><Trash2 size={16} /></button></div></div>)}<button className="mt-2 inline-flex items-center gap-1 text-sm font-medium text-[#14352d] dark:text-emerald-300" onClick={onAdd} type="button"><Plus size={16} /> Agregar</button></div>; }
