"use client"

import { AlertTriangle, ArrowLeft, BellRing, Building2, CalendarClock, CheckCircle2, Download, Eye, FileCheck2, Info, Link2, MoreHorizontal, Send, ShieldAlert, UserRound } from "lucide-react"
import Link from "next/link"
import { useState } from "react"

import { ComplianceScore, ScoreScale } from "@/components/compliance-score"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"

type FindingStatus = "Pendiente" | "En gestión" | "Subsanada" | "Riesgo aceptado"

const initialFindings = [
  { id: 1, item: "Junta directiva fuera de vigencia", section: "Datos generales", severity: "Alta", status: "En gestión" as FindingStatus, owner: "María Pérez", due: "05 ago 2026", source: "Estatutos y Código de Comercio · artículo por validar" },
  { id: 2, item: "Libro auxiliar de ventas presenta atraso", section: "Verificaciones en sitio", severity: "Crítica", status: "Pendiente" as FindingStatus, owner: "José Torres", due: "02 ago 2026", source: "Normativa IVA · artículo por validar" },
  { id: 3, item: "Solvencia FAOV no disponible", section: "Vivienda y hábitat", severity: "Alta", status: "Pendiente" as FindingStatus, owner: "Andrea Castillo", due: "05 ago 2026", source: "Ley del Régimen Prestacional de Vivienda y Hábitat · revisar" },
  { id: 4, item: "Última acta de asamblea sin copia certificada", section: "Datos generales", severity: "Media", status: "Riesgo aceptado" as FindingStatus, owner: "María Pérez", due: "Sin recordatorio", source: "Registro mercantil · fuente por validar" },
]

export function ComplianceReport() {
  const [findings, setFindings] = useState(initialFindings)
  const [notice, setNotice] = useState("")
  const notify = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(""), 3800) }
  const update = (id: number, status: FindingStatus) => { setFindings((items) => items.map((item) => item.id === id ? { ...item, status } : item)); notify(status === "Riesgo aceptado" ? "Riesgo aceptado y documentado. El hallazgo continúa afectando el índice." : `Hallazgo actualizado a “${status}”.`) }

  return (
    <main className="min-h-screen bg-[#f7f7f4] text-stone-900 dark:bg-stone-950 dark:text-stone-100">
      {notice && <div className="fixed right-4 top-20 z-50 max-w-md rounded-xl border border-stone-200 bg-white p-4 text-sm shadow-xl dark:border-stone-700 dark:bg-stone-900" role="status">{notice}</div>}
      <div className="mx-auto max-w-7xl px-4 py-7 sm:px-6 lg:px-10">
        <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><Link className="inline-flex items-center gap-1.5 text-sm text-stone-500 hover:text-stone-900" href="/cumplimiento"><ArrowLeft size={15} /> Evaluaciones</Link><div className="mt-3 flex flex-wrap items-center gap-2"><Badge className="border-sky-200 bg-sky-50 text-sky-700" variant="outline">En seguimiento</Badge><span className="text-xs text-stone-500">Evaluación DF-2026-008 · versión 0.1</span></div><h1 className="mt-3 text-3xl font-semibold tracking-tight">Informe de cumplimiento formal</h1><p className="mt-2 text-sm text-stone-500">Finalizado el 29 de julio de 2026 por Andrea Castillo</p></div><div className="flex flex-wrap gap-2"><Button onClick={() => notify("La exportación PDF requiere conectar el generador de informes.")} variant="outline"><Download /> Exportar informe</Button><Button onClick={() => notify("Acceso preparado para el portal. El envío real requiere autenticación y correo.")} variant="outline"><Link2 /> Compartir en portal</Button><Button className="bg-[#14352d] hover:bg-[#0e2821]" onClick={() => notify("Recordatorios actualizados para los hallazgos abiertos.")}><BellRing /> Programar seguimiento</Button></div></div>

        <Card className="mt-6 border-0 shadow-sm"><CardContent className="grid gap-5 pt-4 md:grid-cols-[1fr_auto] md:items-center"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-emerald-50 text-[#276252] dark:bg-emerald-950"><Building2 size={20} /></span><div><p className="text-lg font-semibold">Distribuidora El Roble, C.A.</p><p className="mt-1 text-sm text-stone-500">J-30124567-8 · Municipio Maracaibo, Zulia</p></div></div><div className="flex flex-wrap gap-4 text-xs text-stone-500 md:justify-end"><span className="inline-flex items-center gap-1.5"><FileCheck2 size={15} /> 62 respuestas</span><span className="inline-flex items-center gap-1.5"><UserRound size={15} /> Responsable: María Pérez</span><span className="inline-flex items-center gap-1.5"><Eye size={15} /> Cliente aún no notificado</span></div></CardContent></Card>

        <section className="mt-6 grid gap-5 xl:grid-cols-[0.72fr_1.28fr]">
          <Card className="border-0 shadow-sm"><CardHeader><CardTitle>Índice de preparación</CardTitle><CardDescription>Metodología interna · no constituye garantía</CardDescription></CardHeader><CardContent><ComplianceScore score={68} /><div className="mt-6"><ScoreScale /></div><div className="mt-6 grid grid-cols-3 gap-2 text-center"><SmallStat label="Cumple" value="41" tone="text-emerald-700" /><SmallStat label="No cumple" value="14" tone="text-rose-700" /><SmallStat label="No aplica" value="7" tone="text-stone-500" /></div></CardContent></Card>

          <Card className="border-0 shadow-sm"><CardHeader><CardTitle>Lectura del resultado</CardTitle><CardDescription>Resumen ejecutivo para la firma y el cliente</CardDescription></CardHeader><CardContent><div className="flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><ShieldAlert className="mt-0.5 shrink-0" size={19} /><div><p className="font-semibold">Nivel en desarrollo · requiere plan de acción</p><p className="mt-1 leading-6">Se identificaron 14 debilidades aplicables. Tres son de atención prioritaria por su posible exposición tributaria, municipal o parafiscal.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Insight title="Fortalezas observadas" icon={CheckCircle2} tone="emerald" text="RIF vigente, permisos operativos básicos disponibles y registros laborales consistentes con la nómina." /><Insight title="Exposición principal" icon={AlertTriangle} tone="rose" text="Atraso en libros de IVA, solvencia FAOV no disponible y vigencia societaria pendiente de actualización." /><Insight title="Próxima revisión" icon={CalendarClock} tone="sky" text="Revisión de avances programada para el 12 de agosto de 2026 con María Pérez." /><Insight title="Posibles sanciones" icon={Info} tone="amber" text="No se muestran montos hasta aprobar fuente, artículo, unidad de cálculo, vigencia y aplicabilidad." /></div></CardContent></Card>
        </section>

        <Card className="mt-6 border-0 shadow-sm"><CardHeader className="flex-row items-start justify-between"><div><CardTitle>Plan de subsanación</CardTitle><CardDescription className="mt-1">Cada debilidad conserva responsable, fecha, evidencia y decisión del cliente</CardDescription></div><Badge variant="outline">{findings.filter((item) => item.status === "Subsanada").length} de {findings.length} cerradas</Badge></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-stone-50 text-xs text-stone-500 dark:bg-stone-800/50"><tr><th className="px-5 py-3 font-medium">Hallazgo</th><th className="px-4 py-3 font-medium">Severidad</th><th className="px-4 py-3 font-medium">Estado</th><th className="px-4 py-3 font-medium">Responsable</th><th className="px-4 py-3 font-medium">Recordatorio</th><th className="px-5 py-3 text-right font-medium">Acciones</th></tr></thead><tbody className="divide-y divide-stone-100 dark:divide-stone-800">{findings.map((finding) => <FindingRow finding={finding} key={finding.id} update={update} />)}</tbody></table></div></CardContent></Card>

        <div className="mt-6 grid gap-4 lg:grid-cols-2"><div className="flex gap-3 rounded-xl border border-stone-200 bg-white p-4 text-sm dark:border-stone-800 dark:bg-stone-900"><Send className="mt-0.5 shrink-0 text-[#276252]" size={18} /><div><p className="font-semibold">Acceso del cliente</p><p className="mt-1 leading-6 text-stone-500">El informe se comparte dentro de la cuenta del cliente. El enlace no será público y respetará la empresa asignada a su usuario.</p></div></div><div className="flex gap-3 rounded-xl border border-stone-200 bg-white p-4 text-sm dark:border-stone-800 dark:bg-stone-900"><Info className="mt-0.5 shrink-0 text-stone-500" size={18} /><div><p className="font-semibold">Trazabilidad</p><p className="mt-1 leading-6 text-stone-500">Subsanar o aceptar un riesgo exige comentario, responsable, fecha y evidencia. El historial no debe eliminarse.</p></div></div></div>
      </div>
    </main>
  )
}

function FindingRow({ finding, update }: { finding: (typeof initialFindings)[number]; update: (id: number, status: FindingStatus) => void }) {
  const statusStyle: Record<FindingStatus, string> = { Pendiente: "border-rose-200 bg-rose-50 text-rose-700", "En gestión": "border-sky-200 bg-sky-50 text-sky-700", Subsanada: "border-emerald-200 bg-emerald-50 text-emerald-700", "Riesgo aceptado": "border-amber-200 bg-amber-50 text-amber-700" }
  return <tr><td className="px-5 py-4"><p className="font-semibold">{finding.item}</p><p className="mt-1 text-xs text-stone-500">{finding.section} · {finding.source}</p></td><td className="px-4 py-4"><Badge className={finding.severity === "Crítica" ? "border-rose-200 bg-rose-50 text-rose-700" : finding.severity === "Alta" ? "border-amber-200 bg-amber-50 text-amber-700" : "border-sky-200 bg-sky-50 text-sky-700"} variant="outline">{finding.severity}</Badge></td><td className="px-4 py-4"><Badge className={statusStyle[finding.status]} variant="outline">{finding.status}</Badge></td><td className="px-4 py-4 text-xs"><UserRound className="mr-1.5 inline text-stone-400" size={14} />{finding.owner}</td><td className="px-4 py-4 text-xs text-stone-500"><CalendarClock className="mr-1.5 inline" size={14} />{finding.due}</td><td className="px-5 py-4 text-right"><Button disabled={finding.status === "Subsanada"} onClick={() => update(finding.id, "Subsanada")} size="sm" variant="ghost">Subsanar</Button><Button disabled={finding.status === "Riesgo aceptado"} onClick={() => update(finding.id, "Riesgo aceptado")} size="sm" variant="ghost">Aceptar riesgo</Button><Button aria-label={`Más acciones de ${finding.item}`} size="icon-sm" variant="ghost"><MoreHorizontal /></Button></td></tr>
}

function Insight({ title, text, icon: Icon, tone }: { title: string; text: string; icon: typeof Info; tone: "emerald" | "rose" | "sky" | "amber" }) { const styles = { emerald: "bg-emerald-50 text-emerald-600", rose: "bg-rose-50 text-rose-600", sky: "bg-sky-50 text-sky-600", amber: "bg-amber-50 text-amber-600" }; return <div className="rounded-xl border border-stone-200 p-4 dark:border-stone-700"><span className={`grid size-8 place-items-center rounded-lg ${styles[tone]}`}><Icon size={16} /></span><p className="mt-3 text-sm font-semibold">{title}</p><p className="mt-1 text-xs leading-5 text-stone-500">{text}</p></div> }
function SmallStat({ label, value, tone }: { label: string; value: string; tone: string }) { return <div className="rounded-xl bg-stone-50 p-3 dark:bg-stone-800"><p className={`text-xl font-semibold ${tone}`}>{value}</p><p className="mt-1 text-xs text-stone-500">{label}</p></div> }
