"use client";;
import { CalendarDays, ChevronRight, CircleAlert, FileText, Plus, ReceiptText, Search } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

import { Input } from "@/components/ui/input";
import { SimpleSelect } from "@/components/ui/simple-select";
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table";

type Status = "En preparación" | "Listo para revisión" | "Declarada" | "Pagada";
type Declaration = { id: string; tax: string; period: string; cadence: string; deadlineBasis: string; due: string; status: Status; amount: string; owner: string };

const declarations: Declaration[] = [
  { id: "inces-q2", tax: "INCES · 2do trimestre", period: "Abril a junio 2026", cadence: "Trimestral", deadlineBasis: "Regla pendiente de configurar", due: "Por configurar", status: "En preparación", amount: "Bs. 2.996,10", owner: "MA" },
  { id: "faov-jun", tax: "FAOV · Fondo de Ahorro Obligatorio", period: "Junio 2026", cadence: "Mensual", deadlineBasis: "Regla pendiente de configurar", due: "Por configurar", status: "En preparación", amount: "—", owner: "MA" },
  { id: "dpp-jun", tax: "DPP · Protección a las pensiones", period: "Junio 2026", cadence: "Mensual", deadlineBasis: "Regla configurada en la firma", due: "27 jul 2026", status: "En preparación", amount: "Bs. 53.829,10", owner: "MA" },
  { id: "ivss-jun", tax: "IVSS · Seguro Social", period: "Junio 2026", cadence: "Mensual", deadlineBasis: "5 días continuos · período siguiente", due: "Por configurar", status: "En preparación", amount: "Bs. 855,00", owner: "MA" },
  { id: "iva-jun", tax: "IVA", period: "Junio 2026", cadence: "Mensual", deadlineBasis: "15 días hábiles · período siguiente", due: "30 jul 2026", status: "En preparación", amount: "—", owner: "MA" },
  { id: "municipal-main", tax: "Actividades económicas · Municipio principal", period: "Junio 2026", cadence: "Mensual", deadlineBasis: "10 días hábiles · período siguiente", due: "31 jul 2026", status: "En preparación", amount: "Bs. 1.006,72", owner: "MA" },
  { id: "municipal-branch", tax: "Actividades económicas · Sucursal", period: "Junio 2026", cadence: "Mensual", deadlineBasis: "10 días hábiles · período siguiente", due: "31 jul 2026", status: "En preparación", amount: "Bs. 687,60", owner: "MA" },
  { id: "iva-may", tax: "IVA", period: "Mayo 2026", cadence: "Mensual", deadlineBasis: "15 días hábiles · período siguiente", due: "30 jun 2026", status: "Pagada", amount: "Bs. 14.820,00", owner: "MA" },
  { id: "islr-jun", tax: "Retención ISLR", period: "Junio 2026", cadence: "Mensual", deadlineBasis: "Regla configurada en la firma", due: "31 jul 2026", status: "Listo para revisión", amount: "Bs. 8.442,90", owner: "LU" },
];

const styles: Record<Status, string> = {
  "En preparación": "border-sky-200 bg-sky-50 text-sky-700 dark:border-sky-900 dark:bg-sky-950 dark:text-sky-300",
  "Listo para revisión": "border-amber-200 bg-amber-50 text-amber-700 dark:border-amber-900 dark:bg-amber-950 dark:text-amber-300",
  Declarada: "border-violet-200 bg-violet-50 text-violet-700 dark:border-violet-900 dark:bg-violet-950 dark:text-violet-300",
  Pagada: "border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950 dark:text-emerald-300",
};

function declarationHref(tax: string) {
  if (tax === "IVA") return "/declaraciones/iva";
  if (tax.includes("INCES")) return "/declaraciones/inces";
  if (tax.includes("FAOV")) return "/declaraciones/faov";
  if (tax.includes("DPP")) return "/declaraciones/dpp";
  if (tax.includes("IVSS")) return "/declaraciones/ivss";
  if (tax.includes("Actividades económicas")) return "/declaraciones/municipales";
  return null;
}

export function DeclarationsDirectory() {
  const [createOpen, setCreateOpen] = useState(false);
  const [kind, setKind] = useState("IVA");
  const [period, setPeriod] = useState("Junio 2026");
  const isInces = kind === "INCES · Aporte trimestral";
  const periodOptions = isInces ? ["Enero a marzo 2026", "Abril a junio 2026"] : ["Mayo 2026", "Junio 2026"];
  const href = kind === "IVA" ? "/declaraciones/iva" : kind === "IVSS · Seguro Social" ? "/declaraciones/ivss" : kind === "DPP · Protección a las pensiones" ? "/declaraciones/dpp" : kind === "FAOV · Fondo de Ahorro Obligatorio" ? "/declaraciones/faov" : kind === "INCES · Aporte trimestral" ? "/declaraciones/inces" : "/declaraciones/municipales";
  const explanation = kind === "IVA" ? "Se incluirán ventas del período y compras disponibles que el responsable seleccione." : kind === "IVSS · Seguro Social" ? "Se incluirá el personal activo, los lunes del período y la factura descargada del portal." : kind === "DPP · Protección a las pensiones" ? "Se incluirá el personal activo, el ingreso indexado, la tasa BCV de cierre y los cuatro soportes del expediente." : kind === "FAOV · Fondo de Ahorro Obligatorio" ? "Se preparará la nómina con salario integral y el TXT para cargarlo en el portal FAOV." : kind === "INCES · Aporte trimestral" ? "Se consolidará la nómina trimestral y se generará un reporte listo para guardar como PDF." : "Se preparará un expediente por cada alcaldía y sucursal configurada.";

  return (
    <div className="mx-auto max-w-7xl px-4 py-7 sm:px-6 lg:px-10">
      <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm text-stone-500">Empresa activa / Cumplimiento tributario</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Declaraciones</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-stone-600 dark:text-stone-300">Expedientes por impuesto, alcaldía y período. Cada declaración conserva su cálculo, revisión, presentación y evidencias.</p></div><div className="flex flex-wrap gap-2"><Link className="inline-flex h-9 items-center justify-center gap-2 rounded-lg border border-stone-200 bg-white px-3 text-sm font-medium text-stone-700 shadow-sm hover:bg-stone-50 dark:border-stone-700 dark:bg-stone-900 dark:text-stone-200 dark:hover:bg-stone-800" href="/declaraciones/estatus"><CalendarDays size={16} /> Estatus de declaraciones</Link><button className="inline-flex h-9 items-center justify-center gap-2 rounded-lg bg-[#14352d] px-3 text-sm font-medium text-white shadow-sm hover:bg-[#0e2821]" onClick={() => setCreateOpen(true)} type="button"><Plus size={16} /> Crear declaración</button></div></div>
      <div className="mt-7 grid gap-4 sm:grid-cols-3"><Summary label="En preparación" value="7" detail="IVA, DPP, IVSS, FAOV, INCES y 2 alcaldías" tone="sky" /><Summary label="Por revisar" value="1" detail="Pendiente de responsable" tone="amber" /><Summary label="Cerradas" value="1" detail="Con constancias archivadas" tone="emerald" /></div>
      <section className="mt-6 overflow-hidden rounded-xl border border-stone-200 bg-white shadow-sm dark:border-stone-800 dark:bg-stone-900"><div className="flex flex-col gap-3 border-b border-stone-100 p-5 dark:border-stone-800 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">Expedientes del período</h2><p className="mt-1 text-sm text-stone-500">Nueva Confitería del Sur, C.A. · la periodicidad se toma del régimen registrado</p></div><label className="relative"><Search className="absolute left-3 top-2.5 text-stone-400" size={16} /><Input className="field w-56 pl-9" placeholder="Buscar período o impuesto" /></label></div><div className="overflow-x-auto"><Table className="min-w-[900px] w-full text-left text-sm"><TableHeader className="bg-stone-50 text-xs font-medium text-stone-500 dark:bg-stone-800/70"><TableRow><TableHead className="px-5 py-3">Impuesto / período</TableHead><TableHead className="px-3 py-3">Fecha tope</TableHead><TableHead className="px-3 py-3">Responsable</TableHead><TableHead className="px-3 py-3 text-right">Monto declarado</TableHead><TableHead className="px-5 py-3">Estatus</TableHead><TableHead className="w-12 px-5 py-3" /></TableRow></TableHeader><TableBody className="divide-y divide-stone-100 dark:divide-stone-800">{declarations.map((item) => { const itemHref = declarationHref(item.tax); return <TableRow className="hover:bg-stone-50 dark:hover:bg-stone-800/50" key={item.id}><TableCell className="px-5 py-4"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-lg bg-[#e7f0e9] text-[#14352d] dark:bg-emerald-950 dark:text-emerald-200"><ReceiptText size={17} /></div><div><p className="font-medium">{item.tax}</p><p className="mt-0.5 text-xs text-stone-500">{item.period} · {item.cadence}</p></div></div></TableCell><TableCell className="px-3 py-4"><p className="font-medium">{item.due}</p><p className="mt-1 max-w-52 text-xs text-stone-500">{item.deadlineBasis}</p></TableCell><TableCell className="px-3 py-4"><span className="grid size-7 place-items-center rounded-full bg-stone-100 text-xs font-semibold text-stone-600 dark:bg-stone-800 dark:text-stone-300">{item.owner}</span></TableCell><TableCell className="px-3 py-4 text-right font-medium tabular-nums">{item.amount}</TableCell><TableCell className="px-5 py-4"><span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-medium ${styles[item.status]}`}>{item.status}</span></TableCell><TableCell className="px-5 py-4">{itemHref ? <Link aria-label={`Abrir ${item.tax}`} className="grid size-8 place-items-center rounded-lg text-stone-500 hover:bg-stone-100 hover:text-[#14352d] dark:hover:bg-stone-800" href={itemHref}><ChevronRight size={17} /></Link> : <ChevronRight className="text-stone-300" size={17} />}</TableCell></TableRow>; })}</TableBody></Table></div></section>
      {createOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-stone-950/35 p-4"><section className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl dark:bg-stone-900"><div className="flex items-start gap-3"><div className="grid size-10 place-items-center rounded-xl bg-[#e7f0e9] text-[#14352d] dark:bg-emerald-950 dark:text-emerald-200"><FileText size={19} /></div><div><h2 className="font-semibold">Crear declaración</h2><p className="mt-1 text-sm text-stone-500">Se crea como borrador y no altera registros previos.</p></div></div><label className="mt-5 block text-sm font-medium">Tipo de impuesto<SimpleSelect className="field mt-1.5" onChange={(event) => { const nextKind = event.target.value; setKind(nextKind); setPeriod(nextKind === "INCES · Aporte trimestral" ? "Abril a junio 2026" : "Junio 2026"); }} value={kind}><option>IVA</option><option>Actividades económicas</option><option>DPP · Protección a las pensiones</option><option>IVSS · Seguro Social</option><option>FAOV · Fondo de Ahorro Obligatorio</option><option>INCES · Aporte trimestral</option><option disabled>Retención IVA · Próximamente</option><option disabled>Retención ISLR · Próximamente</option></SimpleSelect></label><label className="mt-4 block text-sm font-medium">Período de imposición<SimpleSelect className="field mt-1.5" onChange={(event) => setPeriod(event.target.value)} value={period}>{periodOptions.map((option) => <option key={option}>{option}</option>)}</SimpleSelect></label>{isInces && <p className="mt-2 text-xs text-stone-500">INCES solo permite crear declaraciones de trimestres cerrados.</p>}<div className="mt-4 rounded-lg bg-stone-50 p-3 text-xs leading-5 text-stone-600 dark:bg-stone-800 dark:text-stone-300"><CalendarDays className="mr-1 inline" size={14} /> {explanation}</div><div className="mt-6 flex justify-end gap-2"><button className="h-9 rounded-lg px-3 text-sm font-medium text-stone-600 hover:bg-stone-100 dark:text-stone-300 dark:hover:bg-stone-800" onClick={() => setCreateOpen(false)} type="button">Cancelar</button><Link className="inline-flex h-9 items-center gap-2 rounded-lg bg-[#14352d] px-3 text-sm font-medium text-white hover:bg-[#0e2821]" href={href}>Crear <ChevronRight size={15} /></Link></div></section></div>}
    </div>
  );
}

function Summary({ label, value, detail, tone }: { label: string; value: string; detail: string; tone: "sky" | "amber" | "emerald" }) { const colors = { sky: "bg-sky-50 text-sky-600 dark:bg-sky-950 dark:text-sky-300", amber: "bg-amber-50 text-amber-600 dark:bg-amber-950 dark:text-amber-300", emerald: "bg-emerald-50 text-emerald-600 dark:bg-emerald-950 dark:text-emerald-300" }; return <div className="rounded-xl border border-stone-200 bg-white p-4 shadow-sm dark:border-stone-800 dark:bg-stone-900"><div className="flex items-start justify-between"><div><p className="text-sm text-stone-500">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-stone-500">{detail}</p></div><div className={`grid size-9 place-items-center rounded-lg ${colors[tone]}`}><CircleAlert size={18} /></div></div></div>; }
