import { AlertTriangle, FileClock, FileText } from "lucide-react";
import Link from "next/link";

import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

export function EmployeeSettlements() {
  return <main className="mx-auto w-full max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><header><p className="text-sm text-stone-500">Empresa activa / Empleados / Liquidaciones</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Liquidaciones</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-stone-600 dark:text-stone-300">Expedientes preparados cuando se registra la fecha y el motivo de retiro de un trabajador.</p></header><div className="mt-7 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950 dark:border-amber-900 dark:bg-amber-950/25 dark:text-amber-100"><AlertTriangle className="mr-2 inline" size={16} /><b>Cálculos aún no habilitados.</b> Esta primera versión conserva el retiro y prepara el expediente; las reglas de liquidación se definirán en una iteración posterior.</div><section className="mt-6 overflow-hidden rounded-xl border border-stone-200 bg-white shadow-sm dark:border-stone-800 dark:bg-stone-900"><div className="overflow-x-auto"><Table className="min-w-[780px]"><TableHeader className="bg-stone-50 text-xs text-stone-500 dark:bg-stone-900/50"><TableRow><TableHead className="px-5 py-3">Trabajador</TableHead><TableHead className="px-5 py-3">Fecha de retiro</TableHead><TableHead className="px-5 py-3">Motivo</TableHead><TableHead className="px-5 py-3">Estado</TableHead><TableHead className="px-5 py-3">Monto</TableHead><TableHead className="px-5 py-3 text-right">Acción</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell className="px-5 py-4"><b>Ramón Suárez</b><p className="mt-0.5 text-xs text-stone-500">V-14.508.291 · Coordinador de despacho</p></TableCell><TableCell className="px-5 py-4">31 jul 2026</TableCell><TableCell className="px-5 py-4">Renuncia</TableCell><TableCell className="px-5 py-4"><span className="inline-flex items-center gap-1 rounded-full bg-amber-50 px-2.5 py-1 text-xs font-medium text-amber-700"><FileClock size={13} /> En preparación</span></TableCell><TableCell className="px-5 py-4 text-stone-500">Pendiente de reglas</TableCell><TableCell className="px-5 py-4 text-right"><Button disabled size="sm" variant="outline"><FileText /> Calcular</Button></TableCell></TableRow></TableBody></Table></div></section><p className="mt-5 text-sm text-stone-500">El retiro también permanece visible en la <Link className="font-medium text-[#14352d] underline underline-offset-4 dark:text-emerald-300" href="/empleados/ramon-suarez">ficha del trabajador</Link>.</p></main>;
}
