"use client";;
import { AttachmentInput } from "@/components/ui/attachment-input";
import { CalendarDays, Check, ChevronLeft, ChevronRight, CircleAlert, Clock3, FileCheck2, Filter, ReceiptText, Save, UploadCloud, WalletCards, X } from "lucide-react";
import { useMemo, useState, type ReactNode } from "react";
import Link from "next/link";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

import { Input } from "@/components/ui/input";
import { DatePicker } from "@/components/ui/date-picker";

type WorkStatus = "Pendiente" | "En preparación" | "Declarada" | "Pagada";
type DeadlineStatus = "Vencida" | "Por vencer" | "Al día";
type Obligation = { id: number; company: string; business: string; obligation: string; period: string; cadence: "Mensual" | "Quincenal"; regime: "General" | "SPE"; deadlineBasis: string; due: string; deadline: DeadlineStatus; work: WorkStatus; activity: "Con actividad" | "Sin actividad"; declaredAt: string; amount: string; owner: string };

const initialObligations: Obligation[] = [
  { id: 1, company: "Distribuidora El Roble, C.A.", business: "Distribución de alimentos", obligation: "Impuesto municipal", period: "Junio 2026", cadence: "Mensual", regime: "General", deadlineBasis: "10 días hábiles · inicio del período siguiente", due: "Hoy · 29 jul", deadline: "Vencida", work: "Pendiente", activity: "Con actividad", declaredAt: "2026-07-29", amount: "", owner: "LU" },
  { id: 2, company: "Inversiones Costa Azul, C.A.", business: "Servicios inmobiliarios", obligation: "Declaración de IVA", period: "2da quincena · julio 2026", cadence: "Quincenal", regime: "SPE", deadlineBasis: "Calendario anual SPE · terminal del RIF", due: "30 jul · mañana", deadline: "Por vencer", work: "En preparación", activity: "Con actividad", declaredAt: "2026-07-29", amount: "", owner: "MA" },
  { id: 3, company: "Servicios Maracay, C.A.", business: "Servicios profesionales", obligation: "IVSS · Seguro Social", period: "Junio 2026", cadence: "Mensual", regime: "General", deadlineBasis: "5 días continuos · inicio del período siguiente", due: "31 jul · 2 días", deadline: "Por vencer", work: "En preparación", activity: "Sin actividad", declaredAt: "2026-07-29", amount: "", owner: "JP" },
  { id: 4, company: "Inversiones Costa Azul, C.A.", business: "Servicios inmobiliarios", obligation: "IGTF", period: "2da quincena · julio 2026", cadence: "Quincenal", regime: "SPE", deadlineBasis: "Calendario anual SPE · terminal del RIF", due: "01 ago · 3 días", deadline: "Por vencer", work: "Pendiente", activity: "Con actividad", declaredAt: "2026-07-29", amount: "", owner: "MA" },
  { id: 5, company: "Inversiones Costa Azul, C.A.", business: "Servicios inmobiliarios", obligation: "Retención de IVA", period: "1ra quincena · julio 2026", cadence: "Quincenal", regime: "SPE", deadlineBasis: "Calendario anual SPE · terminal del RIF", due: "15 jul", deadline: "Al día", work: "Declarada", activity: "Con actividad", declaredAt: "2026-07-15", amount: "Bs. 5.824,18", owner: "MA" },
];

const deadlineStyle: Record<DeadlineStatus, string> = { Vencida: "border-rose-200 bg-rose-50 text-rose-700 dark:border-rose-900 dark:bg-rose-950 dark:text-rose-300", "Por vencer": "border-amber-200 bg-amber-50 text-amber-700 dark:border-amber-900 dark:bg-amber-950 dark:text-amber-300", "Al día": "border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950 dark:text-emerald-300" };
const workStyle: Record<WorkStatus, string> = { Pendiente: "text-stone-500", "En preparación": "text-sky-600 dark:text-sky-300", Declarada: "text-emerald-600 dark:text-emerald-300", Pagada: "text-emerald-700 dark:text-emerald-200" };

export function FiscalCalendar() {
  const [obligations, setObligations] = useState(initialObligations);
  const [selectedId, setSelectedId] = useState(1);
  const [filter, setFilter] = useState<"Todas" | DeadlineStatus>("Todas");
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [saved, setSaved] = useState(false);
  const selected = obligations.find((item) => item.id === selectedId) ?? obligations[0];
  const visible = useMemo(() => filter === "Todas" ? obligations : obligations.filter((item) => item.deadline === filter), [filter, obligations]);
  const update = (values: Partial<Obligation>) => { setSaved(false); setObligations((items) => items.map((item) => item.id === selectedId ? { ...item, ...values } : item)); };
  const open = (id: number) => { setSelectedId(id); setSaved(false); if (!window.matchMedia("(min-width: 1280px)").matches) setDrawerOpen(true); };
  const save = () => { if (selected.work !== "Pagada") update({ work: "Declarada" }); setSaved(true); };

  return <div className="mx-auto max-w-7xl px-4 py-7 sm:px-6 lg:px-10"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="mb-2 text-sm text-stone-500">Operación tributaria · julio 2026</p><h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">Calendario fiscal</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-stone-600 dark:text-stone-300">Una bandeja de trabajo para actuar primero sobre lo que requiere gestión. Las fechas y el riesgo se calculan automáticamente según las reglas que se configuren.</p></div><div className="flex items-center gap-2"><Button size="sm" variant="outline"><ChevronLeft /> Mes anterior</Button><Button size="sm" variant="outline">Julio 2026 <ChevronRight /></Button></div></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={CircleAlert} label="Requieren gestión" value="4" detail="1 vencida · 3 próximas" color="rose" /><Metric icon={Clock3} label="Vencen en 7 días" value="3" detail="En 3 empresas" color="amber" /><Metric icon={FileCheck2} label="Declaradas este mes" value="26" detail="94% de cumplimiento" color="emerald" /><Metric icon={WalletCards} label="Por transferir" value="Bs. 0,00" detail="Pagos por conciliar" color="sky" /></div>
    <Card className="mt-6 border-0 shadow-sm"><CardContent className="py-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-medium">Avance del período</p><p className="mt-0.5 text-xs text-stone-500">26 de 30 obligaciones cerradas</p></div><div className="flex items-center gap-3 text-xs text-stone-500"><span>● 26 declaradas</span><span className="text-amber-600">● 3 próximas</span><span className="text-rose-600">● 1 vencida</span></div></div><div className="mt-3 flex h-2 overflow-hidden rounded-full bg-stone-100 dark:bg-stone-800"><span className="w-[87%] bg-emerald-500" /><span className="w-[10%] bg-amber-500" /><span className="w-[3%] bg-rose-500" /></div></CardContent></Card>
    <div className="mt-6 xl:grid xl:grid-cols-[minmax(0,1fr)_23rem] xl:gap-6"><section><div className="mb-3 flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div className="flex items-center gap-2"><Filter size={17} className="text-stone-500" /><div className="flex gap-1 overflow-x-auto"><Chip active={filter === "Todas"} label="Todas" onClick={() => setFilter("Todas")} />{(["Vencida", "Por vencer", "Al día"] as DeadlineStatus[]).map((item) => <Chip active={filter === item} key={item} label={item} onClick={() => setFilter(item)} />)}</div></div><Link className="text-sm font-medium text-[#14352d] hover:underline dark:text-emerald-300" href="/calendario/matriz">Matriz completa</Link></div><Card className="border-0 shadow-sm"><CardHeader className="border-b border-stone-100 dark:border-stone-800"><CardTitle>Obligaciones del período</CardTitle><CardDescription className="mt-1">La periodicidad y la regla usada acompañan cada fecha tope.</CardDescription></CardHeader><CardContent className="p-0"><div className="divide-y divide-stone-100 dark:divide-stone-800">{visible.map((item) => <button className={`grid w-full gap-3 p-4 text-left transition sm:grid-cols-[auto_minmax(0,1fr)_auto_auto] sm:items-center ${selectedId === item.id ? "bg-[#f1f7f2] dark:bg-emerald-950/40" : "hover:bg-stone-50 dark:hover:bg-stone-800/60"}`} key={item.id} onClick={() => open(item.id)} type="button"><div className="grid size-10 place-items-center rounded-lg bg-stone-100 text-stone-500 dark:bg-stone-800 dark:text-stone-300"><CalendarDays size={18} /></div><div className="min-w-0"><p className="truncate text-sm font-semibold">{item.company}</p><p className="mt-0.5 text-sm text-stone-600 dark:text-stone-300">{item.obligation} <span className="text-stone-400">· {item.period}</span></p><p className="mt-1 text-xs text-stone-500">{item.cadence}{item.regime === "SPE" ? " · Sujeto pasivo especial" : ""}</p><p className={`mt-1 text-xs font-medium ${workStyle[item.work]}`}>Trabajo: {item.work}</p></div><div className="text-left sm:text-right"><p className="text-xs text-stone-500">Fecha tope</p><p className="mt-0.5 text-sm font-medium">{item.due}</p><p className="mt-1 max-w-52 text-xs text-stone-500">{item.deadlineBasis}</p></div><Badge className={`${deadlineStyle[item.deadline]} justify-self-start sm:justify-self-end`} variant="outline">{item.deadline}</Badge></button>)}</div></CardContent></Card></section>
      <aside className="sticky top-22 hidden rounded-xl border border-stone-200 bg-white p-5 shadow-sm dark:border-stone-800 dark:bg-stone-900 xl:block"><ComplianceForm item={selected} onSave={save} onUpdate={update} saved={saved} /></aside></div>
    {drawerOpen && <div className="fixed inset-0 z-50 bg-stone-950/35 xl:hidden"><div className="absolute inset-x-0 bottom-0 max-h-[90vh] overflow-y-auto rounded-t-2xl bg-white p-5 shadow-2xl dark:bg-stone-900 sm:inset-y-0 sm:right-0 sm:left-auto sm:w-105 sm:rounded-l-2xl sm:rounded-tr-none"><button aria-label="Cerrar" className="absolute right-4 top-4 grid size-9 place-items-center rounded-lg text-stone-500 hover:bg-stone-100 dark:hover:bg-stone-800" onClick={() => setDrawerOpen(false)} type="button"><X size={19} /></button><ComplianceForm item={selected} onSave={() => { save(); setDrawerOpen(false); }} onUpdate={update} saved={saved} /></div></div>}</div>;
}

function ComplianceForm({ item, onUpdate, onSave, saved }: { item: Obligation; onUpdate: (values: Partial<Obligation>) => void; onSave: () => void; saved: boolean }) { const informative = item.activity === "Sin actividad"; return (
  <><div className="pr-8"><p className="text-xs font-medium uppercase tracking-wide text-stone-500">Registrar cumplimiento</p><h2 className="mt-1 text-base font-semibold">{item.obligation}</h2><p className="mt-1 text-sm text-stone-500">{item.company}</p><div className="mt-3 rounded-lg bg-stone-100 px-3 py-2 text-xs text-stone-600 dark:bg-stone-800 dark:text-stone-300"><p className="font-semibold">{item.cadence}{item.regime === "SPE" ? " · Régimen SPE" : ""}</p><p className="mt-1">{item.deadlineBasis}</p><p className="mt-1 text-stone-500">El estatus se calcula automáticamente y no se edita aquí.</p></div></div><div className="mt-5 space-y-4"><Field label="Tipo de declaración"><div className="grid grid-cols-2 gap-2"><Choice active={!informative} label="Con actividad" onClick={() => onUpdate({ activity: "Con actividad" })} /><Choice active={informative} label="Sin actividad" onClick={() => onUpdate({ activity: "Sin actividad", amount: "" })} /></div></Field><Field label="Fecha declarada"><DatePicker
    className="field"
    onChange={(event) => onUpdate({ declaredAt: event.target.value })}
    value={item.declaredAt || "2026-07-29"} /></Field>{!informative && <Field label="Monto pagado"><Input className="field" onChange={(event) => onUpdate({ amount: event.target.value })} placeholder="Bs. 0,00" value={item.amount} /></Field>}<div><p className="mb-2 text-xs font-medium text-stone-600 dark:text-stone-300">Evidencias</p><div className="grid gap-2"><Dropzone label="Comprobante de declaración" required /><Dropzone label="Declaración" required />{!informative && <><Dropzone label="Planilla de pago" /><Dropzone label="Comprobante de pago" note="Al adjuntarlo se marcará como pagada." onAttached={() => onUpdate({ work: "Pagada" })} /></>}{informative && <Dropzone label="Solvencia (si aplica)" note="Opcional para este tributo." />}</div></div></div><Button className="mt-5 w-full bg-[#14352d] hover:bg-[#0e2821]" onClick={onSave}><Save /> Guardar declaración</Button>{saved && <p className="mt-3 flex items-center gap-1.5 text-xs font-medium text-emerald-700 dark:text-emerald-300"><Check size={15} /> Registro guardado como {item.work === "Pagada" ? "pagado" : "declarado"}.</p>}</>
);
}
function Dropzone({ label, note, required = false, onAttached }: { label: string; note?: string; required?: boolean; onAttached?: () => void }) { const [fileName, setFileName] = useState(""); const attach = (file?: File) => { if (!file) return; setFileName(file.name); onAttached?.(); }; return <label className="flex cursor-pointer items-center gap-3 rounded-lg border border-dashed border-stone-300 px-3 py-2.5 hover:border-[#14352d] hover:bg-stone-50 dark:border-stone-700 dark:hover:bg-stone-800" onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); attach(event.dataTransfer.files[0]); }}><UploadCloud size={17} className="shrink-0 text-stone-500" /><span className="min-w-0"><span className="block text-sm font-medium">{label}{required && <span className="ml-1 text-rose-500">*</span>}</span>{fileName ? <span className="block truncate text-xs font-medium text-emerald-600 dark:text-emerald-300">Adjunto: {fileName}</span> : <>{note && <span className="block text-xs text-stone-500">{note}</span>}<span className="block text-xs text-stone-400">Arrastra un archivo o selecciona</span></>}</span><AttachmentInput className="sr-only" onChange={(event) => attach(event.target.files?.[0])} /></label>; }
function Choice({ active, label, onClick }: { active: boolean; label: string; onClick: () => void }) { return <button className={`rounded-lg border px-2 py-2 text-sm font-medium ${active ? "border-[#14352d] bg-[#e7f0e9] text-[#14352d] dark:border-emerald-700 dark:bg-emerald-950 dark:text-emerald-100" : "border-stone-200 text-stone-600 dark:border-stone-700 dark:text-stone-300"}`} onClick={onClick} type="button">{label}</button>; }
function Metric({ icon: Icon, label, value, detail, color }: { icon: typeof CalendarDays; label: string; value: string; detail: string; color: "rose" | "amber" | "emerald" | "sky" }) { const colors = { rose: "bg-rose-50 text-rose-600 dark:bg-rose-950 dark:text-rose-300", amber: "bg-amber-50 text-amber-600 dark:bg-amber-950 dark:text-amber-300", emerald: "bg-emerald-50 text-emerald-600 dark:bg-emerald-950 dark:text-emerald-300", sky: "bg-sky-50 text-sky-600 dark:bg-sky-950 dark:text-sky-300" }; return <Card className="border-0 shadow-sm"><CardContent className="flex items-start justify-between pt-4"><div><p className="text-sm text-stone-500">{label}</p><p className="mt-2 text-2xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-xs text-stone-500">{detail}</p></div><div className={`grid size-9 place-items-center rounded-lg ${colors[color]}`}><Icon size={18} /></div></CardContent></Card>; }
function Chip({ active, label, onClick }: { active: boolean; label: string; onClick: () => void }) { return <button className={`shrink-0 rounded-full px-3 py-1.5 text-xs font-medium ${active ? "bg-[#14352d] text-white" : "bg-white text-stone-600 ring-1 ring-stone-200 hover:bg-stone-50 dark:bg-stone-900 dark:text-stone-300 dark:ring-stone-700 dark:hover:bg-stone-800"}`} onClick={onClick} type="button">{label}</button>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block text-xs font-medium text-stone-600 dark:text-stone-300"><span className="mb-1.5 block">{label}</span>{children}</label>; }
