"use client";;
import { Building2, Check, ChevronLeft, ChevronRight, FileText, Landmark, LockKeyhole, Minus, Plus, UsersRound } from "lucide-react";
import { useState } from "react";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

import { Input } from "@/components/ui/input";
import { DatePicker } from "@/components/ui/date-picker";
import { SimpleSelect } from "@/components/ui/simple-select";

const steps = [{ label: "Identidad", icon: Building2 }, { label: "Legal", icon: Landmark }, { label: "Servicio", icon: FileText }, { label: "Accesos", icon: UsersRound }];
const obligations = ["IVA", "Retenciones de IVA", "Retenciones de ISLR", "Impuesto municipal", "IGTF", "IVSS", "FAOV", "INCES", "Parafiscales", "Patente o licencia de actividades", "Servicios públicos"];

export function NewCompanyWizard() {
  const [step, setStep] = useState(0);
  const [branches, setBranches] = useState(false);
  const [branchCount, setBranchCount] = useState(1);
  const [officerCount, setOfficerCount] = useState(1);
  const [clientPortal, setClientPortal] = useState(false);
  const [restrictedAccess, setRestrictedAccess] = useState(false);
  const current = steps[step];
  const StepIcon = current.icon;

  return <>
    <div className="mt-7 grid gap-2 sm:grid-cols-4">{steps.map((item, index) => {
      const Icon = item.icon; const active = index === step; const done = index < step;
      return <button aria-current={active ? "step" : undefined} className={`flex items-center gap-2 rounded-xl border px-3 py-3 text-left text-sm transition ${active ? "border-[#14352d] bg-[#14352d] text-white dark:border-emerald-500 dark:bg-emerald-500 dark:text-stone-950" : done ? "border-emerald-200 bg-emerald-50 text-emerald-900 dark:border-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-200" : "border-stone-200 bg-white text-stone-500 dark:border-stone-800 dark:bg-stone-900 dark:text-stone-400"}`} key={item.label} onClick={() => setStep(index)} type="button"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-black/10 text-xs font-semibold">{done ? <Check size={15} /> : <Icon size={15} />}</span><span><span className="block text-xs opacity-70">Paso {index + 1}</span>{item.label}</span></button>;
    })}</div>
    <Card className="mt-5 border-stone-200 shadow-sm dark:border-stone-800">
      <CardHeader className="border-b border-stone-100 dark:border-stone-800"><div className="flex items-start gap-3"><div className="grid size-10 place-items-center rounded-xl bg-[#e8f1ec] text-[#14352d] dark:bg-emerald-950 dark:text-emerald-300"><StepIcon size={19} /></div><div><CardTitle>{step === 0 && "Identidad fiscal"}{step === 1 && "Expediente legal y gobierno corporativo"}{step === 2 && "Plan y obligaciones a controlar"}{step === 3 && "Accesos y portal del cliente"}</CardTitle><CardDescription className="mt-1">{step === 0 && "Datos base, domicilio fiscal y sucursales."}{step === 1 && "Añade cada cargo y responsable de acuerdo con el documento constitutivo."}{step === 2 && "El plan define el servicio; selecciona las obligaciones que deben vigilarse."}{step === 3 && "Activa cada acceso de forma explícita; ambos son independientes."}</CardDescription></div></div></CardHeader>
      <CardContent className="pt-6">
        {step === 0 && <IdentityStep branches={branches} branchCount={branchCount} setBranchCount={setBranchCount} setBranches={setBranches} />}
        {step === 1 && <LegalStep officerCount={officerCount} setOfficerCount={setOfficerCount} />}
        {step === 2 && <ServiceStep />}
        {step === 3 && <AccessStep clientPortal={clientPortal} restrictedAccess={restrictedAccess} setClientPortal={setClientPortal} setRestrictedAccess={setRestrictedAccess} />}
        <div className="mt-7 flex items-center justify-between border-t border-stone-100 pt-5 dark:border-stone-800"><Button disabled={step === 0} onClick={() => setStep((value) => value - 1)} type="button" variant="outline"><ChevronLeft size={16} /> Anterior</Button>{step < steps.length - 1 ? <Button className="bg-[#14352d] hover:bg-[#0e2821] dark:bg-emerald-500 dark:text-stone-950 dark:hover:bg-emerald-400" onClick={() => setStep((value) => value + 1)} type="button">Continuar <ChevronRight size={16} /></Button> : <Button className="bg-[#14352d] hover:bg-[#0e2821] dark:bg-emerald-500 dark:text-stone-950 dark:hover:bg-emerald-400" type="button"><Check size={16} /> Crear empresa</Button>}</div>
      </CardContent>
    </Card>
  </>;
}

function IdentityStep({ branches, branchCount, setBranches, setBranchCount }: { branches: boolean; branchCount: number; setBranches: (value: boolean) => void; setBranchCount: (value: number) => void }) {
  return <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Razón social" placeholder="Ej. Inversiones ABC, C.A." /><Field label="RIF" placeholder="J-00000000-0" /><SelectField label="Tipo de contribuyente" options={["Ordinario", "Sujeto pasivo especial", "Exento o exonerado", "Por definir"]} /><Field label="Actividad económica" placeholder="Ej. Comercio al mayor" /><div className="sm:col-span-2"><Field label="Dirección fiscal" placeholder="Estado, municipio, parroquia, avenida, edificio y referencia" /></div><Field label="Contacto principal" placeholder="Nombre y apellido" /><Field label="Correo de contacto" placeholder="correo@empresa.com" type="email" /></div><section className="rounded-xl border border-stone-200 p-4 dark:border-stone-800"><p className="text-sm font-semibold">Registros patronales</p><p className="mt-1 text-xs leading-5 text-stone-500">Se usan para preparar los expedientes IVSS y FAOV de esta empresa.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Número patronal · IVSS" placeholder="Ej. 123456789" /><Field label="N.º de afiliación de nómina · FAOV" placeholder="Ej. 0321085357530000000" /></div></section><label className="flex cursor-pointer items-center gap-3 rounded-xl border border-stone-200 p-3 text-sm dark:border-stone-800"><input checked={branches} className="size-4 accent-[#14352d]" onChange={(event) => setBranches(event.target.checked)} type="checkbox" /> <span><span className="font-medium">Esta empresa posee sucursales</span><span className="ml-2 text-xs text-stone-500">Agrega sus direcciones ahora.</span></span></label>{branches && <div className="rounded-xl border border-[#a8c6b5] bg-[#f4faf6] p-4 dark:border-emerald-900 dark:bg-emerald-950/20"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-semibold text-[#14352d] dark:text-emerald-200">Sucursales</p><p className="text-xs text-stone-600 dark:text-stone-300">Cada sucursal tendrá su propia dirección y podrá configurarse después con más detalle.</p></div><Button onClick={() => setBranchCount(branchCount + 1)} size="sm" type="button" variant="outline"><Plus size={15} /> Añadir</Button></div><div className="mt-4 space-y-3">{Array.from({ length: branchCount }, (_, index) => <div className="grid gap-3 rounded-lg border border-emerald-100 bg-white p-3 sm:grid-cols-[1fr_2fr_auto] dark:border-emerald-950 dark:bg-stone-950" key={index}><Field label={`Sucursal ${index + 1}`} placeholder="Ej. Sucursal Valencia" /><Field label="Dirección" placeholder="Estado, municipio y referencia" />{branchCount > 1 && <Button aria-label={`Eliminar sucursal ${index + 1}`} className="self-end" onClick={() => setBranchCount(branchCount - 1)} size="icon" type="button" variant="ghost"><Minus size={16} /></Button>}</div>)}</div></div>}</div>;
}

function LegalStep({ officerCount, setOfficerCount }: { officerCount: number; setOfficerCount: (value: number) => void }) {
  return <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Fecha de constitución" type="date" /><Field label="Capital social / estructura patrimonial" placeholder="Ej. Bs. 100.000; 60% / 40%" /><Field label="Comisario" placeholder="Nombre o firma" /><Field label="Vencimiento del comisario" type="date" /><Field label="Próxima asamblea ordinaria" type="date" /><Field label="Fecha tope de renovación relevante" type="date" /></div><div className="rounded-xl border border-stone-200 p-4 dark:border-stone-800"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-semibold">Cargos y responsables</p><p className="mt-1 text-xs text-stone-500">No se imponen nombres: registra exactamente los cargos definidos por la compañía.</p></div><Button onClick={() => setOfficerCount(officerCount + 1)} size="sm" type="button" variant="outline"><Plus size={15} /> Añadir cargo</Button></div><div className="mt-4 space-y-3">{Array.from({ length: officerCount }, (_, index) => <div className="grid gap-3 rounded-lg bg-stone-50 p-3 sm:grid-cols-[1fr_1fr_auto] dark:bg-stone-900" key={index}><Field label="Cargo" placeholder="Ej. Director general" /><Field label="Nombre completo" placeholder="Nombre y apellido" />{officerCount > 1 && <Button aria-label={`Eliminar cargo ${index + 1}`} className="self-end" onClick={() => setOfficerCount(officerCount - 1)} size="icon" type="button" variant="ghost"><Minus size={16} /></Button>}</div>)}</div></div><div className="rounded-xl border border-dashed border-[#a8c6b5] bg-[#f4faf6] p-4 dark:border-emerald-900 dark:bg-emerald-950/20"><p className="flex items-center gap-2 text-sm font-semibold text-[#14352d] dark:text-emerald-200"><FileText size={17} /> Expediente corporativo</p><p className="mt-1 text-sm text-stone-600 dark:text-stone-300">El acta constitutiva, las actas de asamblea y los nombramientos se cargarán en <strong>Documentos corporativos</strong>, donde cada archivo tendrá responsable, vigencia y alerta de renovación.</p></div></div>;
}

function ServiceStep() { return <div className="space-y-5"><SelectField label="Plan activo" options={["Esencial — obligaciones básicas", "Tributario — calendario y declaraciones", "Integral — contabilidad y acompañamiento"]} /><div><p className="text-sm font-medium">Obligaciones y servicios a controlar</p><p className="mt-1 text-sm text-stone-500 dark:text-stone-400">Esta es una selección inicial. Las reglas, frecuencia y vigencia se configurarán después, sin asumir normas automáticamente.</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{obligations.map((obligation, index) => <label className="flex items-center gap-3 rounded-xl border border-stone-200 p-3 text-sm dark:border-stone-800" key={obligation}><input className="size-4 accent-[#14352d]" defaultChecked={index < 4} type="checkbox" /> {obligation}</label>)}</div></div></div>; }

function AccessStep({ clientPortal, restrictedAccess, setClientPortal, setRestrictedAccess }: { clientPortal: boolean; restrictedAccess: boolean; setClientPortal: (value: boolean) => void; setRestrictedAccess: (value: boolean) => void }) { return <div className="space-y-4"><p className="text-sm text-stone-600 dark:text-stone-300">Marca las opciones que deben habilitarse para esta empresa. No son alternativas excluyentes.</p><label className={`block cursor-pointer rounded-xl border p-4 transition ${clientPortal ? "border-sky-400 bg-sky-50 dark:border-sky-700 dark:bg-sky-950/30" : "border-stone-200 dark:border-stone-800"}`}><div className="flex items-start gap-3"><input checked={clientPortal} className="mt-1 size-4 accent-[#14352d]" onChange={(event) => setClientPortal(event.target.checked)} type="checkbox" /><div className="grid size-9 shrink-0 place-items-center rounded-lg bg-sky-100 text-sky-700 dark:bg-sky-950 dark:text-sky-300"><UsersRound size={18} /></div><div><h3 className="font-semibold">Habilitar portal del cliente</h3><p className="mt-1 text-sm text-stone-600 dark:text-stone-300">Al crear la empresa se enviará una invitación segura al contacto principal. Luego podrás agregar otros usuarios y permisos.</p></div></div></label><label className={`block cursor-pointer rounded-xl border p-4 transition ${restrictedAccess ? "border-amber-400 bg-amber-50 dark:border-amber-700 dark:bg-amber-950/30" : "border-stone-200 dark:border-stone-800"}`}><div className="flex items-start gap-3"><input checked={restrictedAccess} className="mt-1 size-4 accent-[#14352d]" onChange={(event) => setRestrictedAccess(event.target.checked)} type="checkbox" /><div className="grid size-9 shrink-0 place-items-center rounded-lg bg-amber-100 text-amber-800 dark:bg-amber-900/50 dark:text-amber-200"><LockKeyhole size={18} /></div><div><h3 className="font-semibold">Gestionar accesos tributarios restringidos</h3><p className="mt-1 text-sm text-stone-600 dark:text-stone-300">Después de crear la empresa, personas autorizadas podrán registrar credenciales y certificados en un módulo cifrado, por rol y con auditoría.</p></div></div></label></div>; }

function Field({ label, placeholder, type = "text" }: { label: string; placeholder?: string; type?: string }) { return <label className="text-sm font-medium">{label}{type === "date" ? <DatePicker className="mt-1.5" placeholder={placeholder ?? "Seleccionar fecha"} /> : <Input className="field mt-1.5" placeholder={placeholder} type={type} />}</label>; }
function SelectField({ label, options }: { label: string; options: string[] }) { return <label className="text-sm font-medium">{label}<SimpleSelect className="field mt-1.5" defaultValue=""><option disabled value="">Selecciona una opción</option>{options.map((option) => <option key={option}>{option}</option>)}</SimpleSelect></label>; }
