"use client";

import { Building2, CheckCircle2, ChevronLeft, ChevronRight, Edit3, FileSpreadsheet, FileText, FileUp, MoreHorizontal, Plus, Printer, Search, Trash2, UploadCloud, X } from "lucide-react";
import { useMemo, useRef, useState } from "react";

import { Button } from "@/components/ui/button";

type PartyKind = "customer" | "supplier";
type Party = { id: number; legalName: string; rif: string; address: string; primaryAccount: string; counterpartAccount: string };
type Draft = Omit<Party, "id">;

const accounts = ["1.1.03.001 · Cuentas por cobrar clientes", "2.1.01.001 · Cuentas por pagar proveedores", "4.1.01.001 · Ingresos por ventas", "5.1.01.001 · Gastos de compras", "5.1.02.003 · Servicios profesionales", "5.1.03.001 · Gastos de arrendamiento"];
const seed: Record<PartyKind, Party[]> = {
  customer: [{ id: 1, legalName: "Comercializadora San Miguel, C.A.", rif: "J-401256789", address: "Av. Bolívar, Edif. Centro, Maracay, Aragua", primaryAccount: accounts[0], counterpartAccount: accounts[2] }, { id: 2, legalName: "Alimentos La Montaña, C.A.", rif: "J-308774521", address: "Zona Industrial La Hamaca, Maracay, Aragua", primaryAccount: accounts[0], counterpartAccount: accounts[2] }],
  supplier: [{ id: 1, legalName: "Distribuidora Nacional de Empaques, C.A.", rif: "J-405699214", address: "Calle Los Talleres, Valencia, Carabobo", primaryAccount: accounts[3], counterpartAccount: accounts[1] }, { id: 2, legalName: "Insumos Occidente, C.A.", rif: "J-314889623", address: "Av. 15 Delicias, Maracaibo, Zulia", primaryAccount: accounts[4], counterpartAccount: accounts[1] }],
};
const blank = (kind: PartyKind): Draft => ({ legalName: "", rif: "", address: "", primaryAccount: kind === "customer" ? accounts[0] : accounts[3], counterpartAccount: kind === "customer" ? accounts[2] : accounts[1] });

export function PartyDirectory({ kind }: { kind: PartyKind }) {
  const isCustomer = kind === "customer";
  const title = isCustomer ? "Clientes comerciales" : "Proveedores";
  const noun = isCustomer ? "cliente" : "proveedor";
  const primaryLabel = isCustomer ? "Cuenta por cobrar" : "Cuenta de gasto";
  const counterpartLabel = isCustomer ? "Cuenta de ingresos" : "Cuenta por pagar";
  const [parties, setParties] = useState(seed[kind]);
  const [query, setQuery] = useState("");
  const [page, setPage] = useState(1);
  const [itemsPerPage, setItemsPerPage] = useState<25 | 50 | "all">(25);
  const [actionsOpen, setActionsOpen] = useState(false);
  const [importOpen, setImportOpen] = useState(false);
  const [importedFileName, setImportedFileName] = useState("");
  const [editing, setEditing] = useState<Party | null>(null);
  const [formOpen, setFormOpen] = useState(false);
  const [draft, setDraft] = useState<Draft>(blank(kind));
  const filtered = useMemo(() => parties.filter((party) => `${party.legalName} ${party.rif}`.toLowerCase().includes(query.toLowerCase())), [parties, query]);
  const totalPages = itemsPerPage === "all" ? 1 : Math.max(1, Math.ceil(filtered.length / itemsPerPage));
  const currentPage = Math.min(page, totalPages);
  const rows = itemsPerPage === "all" ? filtered : filtered.slice((currentPage - 1) * itemsPerPage, currentPage * itemsPerPage);
  const firstRow = filtered.length === 0 ? 0 : itemsPerPage === "all" ? 1 : (currentPage - 1) * itemsPerPage + 1;
  const lastRow = itemsPerPage === "all" ? filtered.length : Math.min(currentPage * itemsPerPage, filtered.length);

  const openCreate = () => { setEditing(null); setDraft(blank(kind)); setFormOpen(true); };
  const openEdit = (party: Party) => { setEditing(party); setDraft({ legalName: party.legalName, rif: party.rif, address: party.address, primaryAccount: party.primaryAccount, counterpartAccount: party.counterpartAccount }); setFormOpen(true); };
  const remove = (party: Party) => { if (window.confirm(`¿Eliminar ${party.legalName}?`)) setParties((current) => current.filter((item) => item.id !== party.id)); };
  const save = () => { if (!draft.legalName.trim() || !draft.rif.trim()) return; setParties((current) => editing ? current.map((party) => party.id === editing.id ? { ...draft, id: party.id } : party) : [...current, { ...draft, id: Math.max(0, ...current.map((party) => party.id)) + 1 }]); setFormOpen(false); };
  const changeSize = (value: string) => { setItemsPerPage(value === "all" ? "all" : Number(value) as 25 | 50); setPage(1); };
  const download = (format: "csv" | "excel") => { const header = ["Nombre legal", "RIF", "Dirección fiscal", primaryLabel, counterpartLabel]; const data = filtered.map((party) => [party.legalName, party.rif, party.address, party.primaryAccount, party.counterpartAccount]); if (format === "csv") saveFile(new Blob(["\ufeff", [header, ...data].map((row) => row.map((cell) => `"${cell.replaceAll('"', '""')}"`).join(",")).join("\n")], { type: "text/csv;charset=utf-8" }), `${noun}s.csv`); else saveFile(new Blob([`<html><meta charset="UTF-8"><table>${[header, ...data].map((row) => `<tr>${row.map((cell) => `<td>${escapeHtml(cell)}</td>`).join("")}</tr>`).join("")}</table></html>`], { type: "application/vnd.ms-excel" }), `${noun}s.xls`); setActionsOpen(false); };

  return <div className="mx-auto max-w-7xl px-5 py-8 lg:px-10">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm text-stone-500">Empresa activa / Operaciones</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-stone-600 dark:text-stone-300">Registra los datos fiscales y la configuración contable que se aplicará como referencia al cargar operaciones.</p></div><Button className="h-9 bg-[#14352d] hover:bg-[#0e2821]" onClick={openCreate}><Plus /> Nuevo {noun}</Button></div>
    <section className="mt-7 overflow-visible rounded-xl border border-stone-200 bg-white shadow-sm dark:border-stone-800 dark:bg-stone-900">
      <div className="flex flex-col gap-3 border-b border-stone-100 p-4 dark:border-stone-800 sm:flex-row sm:items-center sm:justify-between">
        <div className="relative w-full sm:max-w-md"><Search className="pointer-events-none absolute left-3 top-2.5 text-stone-400" size={16} /><input className="field pl-9" onChange={(event) => { setQuery(event.target.value); setPage(1); }} placeholder="Buscar por nombre legal o RIF..." value={query} /></div>
        <div className="flex items-center justify-between gap-3 sm:justify-end"><label className="flex items-center gap-2 text-xs text-stone-500">Mostrar <select aria-label="Cantidad de registros por página" className="h-8 rounded-lg border border-stone-200 bg-white px-2 text-sm text-stone-700 dark:border-stone-700 dark:bg-stone-800 dark:text-stone-200" onChange={(event) => changeSize(event.target.value)} value={itemsPerPage}><option value="25">25</option><option value="50">50</option><option value="all">Todos</option></select></label><div className="relative"><Button aria-expanded={actionsOpen} aria-label="Opciones de tabla" onClick={() => setActionsOpen((open) => !open)} size="icon-sm" type="button" variant="outline"><MoreHorizontal size={18} /></Button>{actionsOpen && <div className="absolute right-0 top-9 z-20 w-48 rounded-lg border border-stone-200 bg-white p-1 shadow-lg dark:border-stone-700 dark:bg-stone-900"><button className="menu-action" onClick={() => { setActionsOpen(false); setImportOpen(true); }} type="button"><FileUp size={16} /> Importar archivo</button><div className="my-1 border-t border-stone-100 dark:border-stone-800" /><button className="menu-action" onClick={() => download("excel")} type="button"><FileSpreadsheet size={16} /> Exportar Excel</button><button className="menu-action" onClick={() => download("csv")} type="button"><FileText size={16} /> Exportar CSV</button><button className="menu-action" onClick={() => { setActionsOpen(false); window.print(); }} type="button"><FileText size={16} /> Exportar PDF</button><div className="my-1 border-t border-stone-100 dark:border-stone-800" /><button className="menu-action" onClick={() => { setActionsOpen(false); window.print(); }} type="button"><Printer size={16} /> Imprimir</button></div>}</div></div>
      </div>
      {importedFileName && <p className="flex items-center gap-1 px-4 pt-3 text-xs text-emerald-700"><CheckCircle2 size={14} /> Archivo preparado: {importedFileName}</p>}
      <div className="overflow-x-auto"><table className="w-full min-w-[930px] text-left text-sm"><thead className="bg-stone-50 text-xs font-medium text-stone-500 dark:bg-stone-900/50"><tr><th className="px-5 py-3">Nombre legal</th><th className="px-5 py-3">RIF</th><th className="px-5 py-3">Cuenta principal</th><th className="px-5 py-3">Contrapartida</th><th className="px-5 py-3 text-right">Acciones</th></tr></thead><tbody className="divide-y divide-stone-100 dark:divide-stone-800">{rows.map((party) => <tr className="hover:bg-[#f4faf6] dark:hover:bg-emerald-950/10" key={party.id}><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-stone-100 text-stone-500 dark:bg-stone-800"><Building2 size={17} /></span><div><p className="font-medium">{party.legalName}</p><p className="mt-0.5 max-w-xs truncate text-xs text-stone-500">{party.address}</p></div></div></td><td className="px-5 py-4 font-medium">{party.rif}</td><td className="px-5 py-4 text-stone-600 dark:text-stone-300">{party.primaryAccount}</td><td className="px-5 py-4 text-stone-600 dark:text-stone-300">{party.counterpartAccount}</td><td className="px-5 py-4"><div className="flex justify-end gap-1"><Button aria-label={`Editar ${party.legalName}`} onClick={() => openEdit(party)} size="icon-sm" type="button" variant="ghost"><Edit3 size={15} /></Button><Button aria-label={`Eliminar ${party.legalName}`} className="text-rose-600 hover:bg-rose-50 hover:text-rose-700" onClick={() => remove(party)} size="icon-sm" type="button" variant="ghost"><Trash2 size={15} /></Button></div></td></tr>)}{rows.length === 0 && <tr><td className="px-5 py-12 text-center text-stone-500" colSpan={5}>No se encontraron registros.</td></tr>}</tbody></table></div>
      <div className="flex flex-col gap-3 border-t border-stone-100 px-4 py-3 text-sm dark:border-stone-800 sm:flex-row sm:items-center sm:justify-between"><p className="text-stone-500">Mostrando {firstRow}–{lastRow} de {filtered.length} registros</p><div className="flex items-center gap-2"><Button disabled={currentPage === 1} onClick={() => setPage(currentPage - 1)} size="sm" type="button" variant="outline"><ChevronLeft /> Anterior</Button><span className="min-w-20 text-center text-xs text-stone-500">Página {currentPage} de {totalPages}</span><Button disabled={currentPage === totalPages} onClick={() => setPage(currentPage + 1)} size="sm" type="button" variant="outline">Siguiente <ChevronRight /></Button></div></div>
    </section>
    {importOpen && <ImportDialog counterpartLabel={counterpartLabel} onClose={() => setImportOpen(false)} onUpload={(file) => { setImportedFileName(file.name); setImportOpen(false); }} primaryLabel={primaryLabel} title={title} />}
    {formOpen && <PartyFormDialog counterpartLabel={counterpartLabel} draft={draft} editing={editing} noun={noun} onChange={setDraft} onClose={() => setFormOpen(false)} onSave={save} primaryLabel={primaryLabel} />}
  </div>;
}

function ImportDialog({ title, primaryLabel, counterpartLabel, onClose, onUpload }: { title: string; primaryLabel: string; counterpartLabel: string; onClose: () => void; onUpload: (file: File) => void }) { const [file, setFile] = useState<File | null>(null); const ref = useRef<HTMLInputElement>(null); const select = (candidate?: File) => { if (candidate && /\.(csv|xlsx|xls)$/i.test(candidate.name)) setFile(candidate); }; return <div aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-stone-950/35 p-4" role="dialog"><div className="w-full max-w-xl rounded-2xl bg-white shadow-2xl dark:bg-stone-900"><div className="flex justify-between border-b border-stone-100 p-5 dark:border-stone-800"><div><h2 className="text-lg font-semibold">Importar {title.toLowerCase()}</h2><p className="mt-1 text-sm text-stone-500">CSV UTF-8 separado por comas o Excel (.xlsx/.xls).</p></div><Button aria-label="Cerrar" onClick={onClose} size="icon-sm" variant="ghost"><X /></Button></div><div className="space-y-5 p-5"><p className="rounded-lg bg-stone-50 p-4 text-sm text-stone-600 dark:bg-stone-800">Columnas esperadas: Nombre legal, RIF, Dirección fiscal, {primaryLabel} y {counterpartLabel}.</p><input accept=".csv,.xlsx,.xls" className="hidden" onChange={(event) => select(event.target.files?.[0])} ref={ref} type="file" /><button className="flex min-h-40 w-full flex-col items-center justify-center rounded-xl border-2 border-dashed border-stone-300 px-6 text-center hover:border-[#14352d] hover:bg-[#f4faf6]" onClick={() => ref.current?.click()} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); select(event.dataTransfer.files[0]); }} type="button"><UploadCloud className="text-[#14352d]" size={29} /><p className="mt-3 text-sm font-medium">Arrastra el archivo aquí o selecciónalo</p>{file && <p className="mt-3 flex items-center gap-1 text-xs font-medium text-emerald-700"><CheckCircle2 size={14} /> {file.name}</p>}</button></div><div className="flex justify-end gap-2 border-t border-stone-100 p-5"><Button onClick={onClose} variant="outline">Cancelar</Button><Button className="bg-[#14352d] hover:bg-[#0e2821]" disabled={!file} onClick={() => file && onUpload(file)}>Subir y revisar</Button></div></div></div>; }

function PartyFormDialog({ draft, editing, noun, primaryLabel, counterpartLabel, onChange, onClose, onSave }: { draft: Draft; editing: Party | null; noun: string; primaryLabel: string; counterpartLabel: string; onChange: (draft: Draft) => void; onClose: () => void; onSave: () => void }) { const field = (key: keyof Draft) => (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => onChange({ ...draft, [key]: event.target.value }); return <div aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-stone-950/35 p-4" role="dialog"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white shadow-2xl dark:bg-stone-900"><div className="flex justify-between border-b border-stone-100 p-5"><div><h2 className="text-lg font-semibold">{editing ? "Editar" : "Nuevo"} {noun}</h2><p className="mt-1 text-sm text-stone-500">Datos fiscales y configuración contable.</p></div><Button aria-label="Cerrar" onClick={onClose} size="icon-sm" variant="ghost"><X /></Button></div><div className="grid gap-4 p-5 sm:grid-cols-2"><label className="text-sm font-medium sm:col-span-2">Nombre legal *<input className="field mt-1.5" onChange={field("legalName")} value={draft.legalName} /></label><label className="text-sm font-medium">RIF *<div className="mt-1.5 flex gap-2"><input className="field" onChange={field("rif")} value={draft.rif} /><Button disabled size="sm" variant="outline">Consultar SENIAT</Button></div></label><label className="text-sm font-medium">Dirección fiscal<textarea className="field mt-1.5 h-22 py-2" onChange={field("address")} value={draft.address} /></label><Account label={primaryLabel} onChange={field("primaryAccount")} value={draft.primaryAccount} /><Account label={counterpartLabel} onChange={field("counterpartAccount")} value={draft.counterpartAccount} /></div><div className="flex justify-end gap-2 border-t border-stone-100 p-5"><Button onClick={onClose} variant="outline">Cancelar</Button><Button className="bg-[#14352d] hover:bg-[#0e2821]" disabled={!draft.legalName || !draft.rif} onClick={onSave}>Guardar {noun}</Button></div></div></div>; }
function Account({ label, value, onChange }: { label: string; value: string; onChange: (event: React.ChangeEvent<HTMLSelectElement>) => void }) { return <label className="text-sm font-medium">{label}<select className="field mt-1.5" onChange={onChange} value={value}>{accounts.map((account) => <option key={account}>{account}</option>)}</select></label>; }
function saveFile(blob: Blob, name: string) { const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url); }
function escapeHtml(value: string) { return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;"); }
