"use client";

import { Check, CircleAlert, ClipboardList, Landmark, Send } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";

import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

type Commitment = { id: string; concept: string; authority: string; branch: string; due: string; deadlineBasis: string; amount: number; support: boolean };
const commitments: Commitment[] = [
  { id: "iae-main", concept: "Actividades económicas", authority: "Alcaldía · Municipio principal", branch: "Casa matriz", due: "31 jul 2026", deadlineBasis: "10 días hábiles · período siguiente", amount: 1006.72, support: true },
  { id: "iae-branch", concept: "Actividades económicas", authority: "Alcaldía · Municipio de la sucursal", branch: "Sucursal", due: "31 jul 2026", deadlineBasis: "10 días hábiles · período siguiente", amount: 687.6, support: true },
  { id: "cleaning", concept: "Aseo urbano", authority: "Alcaldía · Municipio principal", branch: "Casa matriz", due: "Pendiente de cálculo", deadlineBasis: "10 días hábiles · período siguiente", amount: 3840, support: true },
  { id: "gas", concept: "Gas", authority: "Prestador de gas", branch: "Casa matriz", due: "05 ago 2026", deadlineBasis: "Fecha indicada en factura", amount: 1280, support: true },
  { id: "publicity", concept: "Publicidad", authority: "Alcaldía · Municipio de la sucursal", branch: "Sucursal", due: "Pendiente de cálculo", deadlineBasis: "10 días hábiles · período siguiente", amount: 690, support: false },
];
const money = new Intl.NumberFormat("es-VE", { style: "currency", currency: "VES", minimumFractionDigits: 2 });

export function PaymentCommitments() {
  const [selected, setSelected] = useState(() => new Set(commitments.filter((item) => item.support).map((item) => item.id)));
  const [prepared, setPrepared] = useState(false);
  const chosen = commitments.filter((item) => selected.has(item.id));
  const total = useMemo(() => chosen.reduce((sum, item) => sum + item.amount, 0), [chosen]);
  const toggle = (id: string) => setSelected((current) => { const next = new Set(current); next.has(id) ? next.delete(id) : next.add(id); return next; });

  return <div className="mx-auto max-w-7xl px-4 py-7 sm:px-6 lg:px-10">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm text-stone-500">Empresa activa / Pagos</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Compromisos pendientes de pago</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-stone-600 dark:text-stone-300">Una hoja para preparar las transferencias del cliente. Cada fecha conserva la regla con la que fue calculada.</p></div><Link className="inline-flex h-9 items-center gap-2 rounded-lg border border-stone-200 bg-white px-3 text-sm font-medium hover:bg-stone-50 dark:border-stone-700 dark:bg-stone-900 dark:hover:bg-stone-800" href="/servicios-municipales"><Landmark size={16} /> Registrar servicios</Link></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-3"><Metric label="Compromisos pendientes" value={String(commitments.length)} detail="En julio y agosto" /><Metric label="Listos para solicitar" value={String(commitments.filter((item) => item.support).length)} detail="Con soporte adjunto" /><Metric label="Monto seleccionado" value={money.format(total)} detail={`${chosen.length} compromisos`} /></div>
    <section className="mt-6 overflow-hidden rounded-xl border border-stone-200 bg-white shadow-sm dark:border-stone-800 dark:bg-stone-900"><div className="border-b border-stone-100 p-5 dark:border-stone-800"><h2 className="font-semibold">Hoja de solicitud de transferencia</h2><p className="mt-1 text-sm text-stone-500">Selecciona los pagos que se enviarán al cliente. El pago sigue pendiente hasta que se adjunte el comprobante.</p></div><div className="overflow-x-auto"><Table className="min-w-[900px] w-full text-left text-sm"><TableHeader className="bg-stone-50 text-xs font-medium text-stone-500 dark:bg-stone-800/70"><TableRow><TableHead className="w-12 px-5 py-3">Incluir</TableHead><TableHead className="px-3 py-3">Concepto / organismo</TableHead><TableHead className="px-3 py-3">Sucursal</TableHead><TableHead className="px-3 py-3">Fecha tope</TableHead><TableHead className="px-3 py-3">Soporte</TableHead><TableHead className="px-5 py-3 text-right">Monto</TableHead></TableRow></TableHeader><TableBody className="divide-y divide-stone-100 dark:divide-stone-800">{commitments.map((item) => <TableRow className={selected.has(item.id) ? "bg-emerald-50/35 dark:bg-emerald-950/10" : ""} key={item.id}><TableCell className="px-5 py-4"><input aria-label={`Incluir ${item.concept}`} checked={selected.has(item.id)} className="size-4 accent-[#14352d]" disabled={!item.support} onChange={() => toggle(item.id)} type="checkbox" /></TableCell><TableCell className="px-3 py-4"><p className="font-medium">{item.concept}</p><p className="mt-0.5 text-xs text-stone-500">{item.authority}</p></TableCell><TableCell className="px-3 py-4">{item.branch}</TableCell><TableCell className="px-3 py-4"><p className="font-medium">{item.due}</p><p className="mt-1 max-w-48 text-xs text-stone-500">{item.deadlineBasis}</p></TableCell><TableCell className="px-3 py-4">{item.support ? <span className="inline-flex items-center gap-1 text-xs font-medium text-emerald-700 dark:text-emerald-300"><Check size={14} /> Disponible</span> : <span className="inline-flex items-center gap-1 text-xs font-medium text-amber-700 dark:text-amber-300"><CircleAlert size={14} /> Falta soporte</span>}</TableCell><TableCell className="px-5 py-4 text-right font-medium tabular-nums">{money.format(item.amount)}</TableCell></TableRow>)}</TableBody></Table></div></section>
    <div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1fr)_21rem]"><section className="rounded-xl border border-dashed border-stone-300 bg-white/60 p-5 dark:border-stone-700 dark:bg-stone-900/50"><p className="font-semibold">Qué verá el cliente</p><p className="mt-1 text-sm text-stone-500">Concepto, organismo, sucursal, fecha tope, regla aplicada, monto y documento de respaldo. Las transferencias no se ejecutan desde el sistema.</p></section><aside className="rounded-xl border border-stone-200 bg-white p-5 shadow-sm dark:border-stone-800 dark:bg-stone-900"><div className="flex gap-3"><div className="grid size-9 place-items-center rounded-lg bg-[#e7f0e9] text-[#14352d] dark:bg-emerald-950 dark:text-emerald-200"><ClipboardList size={18} /></div><div><p className="font-semibold">Solicitud actual</p><p className="mt-1 text-sm text-stone-500">{chosen.length} pagos por {money.format(total)}</p></div></div><button className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-lg bg-[#14352d] px-3 py-2.5 text-sm font-medium text-white disabled:opacity-50" disabled={!chosen.length} onClick={() => setPrepared(true)} type="button"><Send size={16} /> Preparar solicitud</button>{prepared && <p className="mt-3 text-xs font-medium text-emerald-700 dark:text-emerald-300">Solicitud preparada para compartir con el cliente.</p>}</aside></div>
  </div>;
}

function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="rounded-xl border border-stone-200 bg-white p-4 shadow-sm dark:border-stone-800 dark:bg-stone-900"><p className="text-sm text-stone-500">{label}</p><p className="mt-2 text-xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-xs text-stone-500">{detail}</p></div>; }
