"use client";

import { AlertTriangle, Check, FileText, Gift, Settings2, X } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { SimpleSelect } from "@/components/ui/simple-select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { employeesDemo, money, type Employee } from "@/lib/employees-demo";

type UtilityLine = { employee: Employee; days: number; amount: number };

export function UtilitiesWorkspace() {
  const [year, setYear] = useState("2026");
  const [regime, setRegime] = useState("ley");
  const [days, setDays] = useState(30);
  const [rate, setRate] = useState("47,50");
  const [created, setCreated] = useState(false);
  const [receipt, setReceipt] = useState<UtilityLine | null>(null);
  const numericRate = Number(rate.replace(",", ".")) || 0;
  const active = employeesDemo.filter((employee) => employee.status !== "Retirado");
  const lines = useMemo<UtilityLine[]>(() => active.map((employee) => ({ employee, days, amount: employee.salary / 30 * days * numericRate })), [active, days, numericRate]);
  const total = lines.reduce((sum, line) => sum + line.amount, 0);
  return (
    <main className="mx-auto w-full max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
      <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm text-stone-500">Empresa activa / Empleados / Utilidades</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Utilidades</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-stone-600 dark:text-stone-300">Prepara el cálculo anual, aplica los días definidos por la empresa y emite recibos individuales.</p></div><Link className="inline-flex h-9 items-center gap-2 rounded-lg border border-stone-200 bg-white px-3 text-sm font-medium dark:border-stone-700 dark:bg-stone-900" href="/configuracion/empresa/laboral"><Settings2 size={16} /> Configuración laboral</Link></header>
      <section className="mt-7 rounded-xl border border-stone-200 bg-white shadow-sm dark:border-stone-800 dark:bg-stone-900"><header className="border-b border-stone-100 p-5 dark:border-stone-800"><h2 className="font-semibold">Crear cálculo anual</h2><p className="mt-1 text-sm text-stone-500">La base definitiva y el prorrateo se completarán al definir las reglas de cada concepto.</p></header><div className="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-4"><Field label="Año"><SimpleSelect className="field mt-1.5" onChange={(event) => setYear(event.target.value)} value={year}><option>2026</option><option>2025</option></SimpleSelect></Field><Field label="Régimen"><SimpleSelect className="field mt-1.5" onChange={(event) => setRegime(event.target.value)} value={regime}><option value="ley">Según regla base</option><option value="especial">Beneficio especial</option></SimpleSelect></Field><Field label="Días de utilidades"><Input className="field mt-1.5" min="30" onChange={(event) => setDays(Number(event.target.value))} type="number" value={days} /></Field><Field label="Tasa aplicada · Bs"><Input className="field mt-1.5" inputMode="decimal" onChange={(event) => setRate(event.target.value)} value={rate} /></Field></div><div className="mx-5 mb-5 rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs leading-5 text-amber-900 dark:border-amber-900 dark:bg-amber-950/25 dark:text-amber-100"><AlertTriangle className="mr-1 inline" size={14} />El mínimo de 30 días y las cifras de esta vista se presentan como parámetros editables, no como validación legal vigente.</div><div className="flex justify-end border-t border-stone-100 p-5 dark:border-stone-800"><Button className="bg-[#14352d] hover:bg-[#0e2821]" disabled={!numericRate || days < 30} onClick={() => setCreated(true)}><Gift /> Preparar utilidades</Button></div></section>
      {created && <p className="mt-5 flex items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950/25 dark:text-emerald-200"><Check size={16} /> Cálculo preparado como borrador para revisión.</p>}
      <section className="mt-6 overflow-hidden rounded-xl border border-stone-200 bg-white shadow-sm dark:border-stone-800 dark:bg-stone-900"><div className="overflow-x-auto"><Table className="min-w-[820px]"><TableHeader className="bg-stone-50 text-xs text-stone-500 dark:bg-stone-900/50"><TableRow><TableHead className="px-5 py-3">Trabajador</TableHead><TableHead className="px-5 py-3">Fecha de ingreso</TableHead><TableHead className="px-5 py-3">Base de referencia</TableHead><TableHead className="px-5 py-3">Días</TableHead><TableHead className="px-5 py-3">Monto estimado</TableHead><TableHead className="px-5 py-3 text-right">Recibo</TableHead></TableRow></TableHeader><TableBody>{lines.map((line) => <TableRow key={line.employee.id}><TableCell className="px-5 py-4"><b>{line.employee.name}</b><p className="mt-0.5 text-xs text-stone-500">{line.employee.identity}</p></TableCell><TableCell className="px-5 py-4">{formatDate(line.employee.admissionDate)}</TableCell><TableCell className="px-5 py-4"><b>{line.employee.salary} {line.employee.salaryCurrency}</b><p className="mt-0.5 text-xs text-stone-500">Salario vigente · provisional</p></TableCell><TableCell className="px-5 py-4">{line.days}</TableCell><TableCell className="px-5 py-4 font-semibold">{created ? money(line.amount) : "Por calcular"}</TableCell><TableCell className="px-5 py-4 text-right"><Button disabled={!created} onClick={() => setReceipt(line)} size="sm" variant="outline"><FileText /> Ver recibo</Button></TableCell></TableRow>)}</TableBody></Table></div>{created && <div className="flex justify-between border-t border-stone-100 bg-stone-50 p-5 dark:border-stone-800 dark:bg-stone-900/50"><b>Total estimado</b><b className="text-lg text-[#14352d] dark:text-emerald-300">{money(total)}</b></div>}</section>
      {receipt && <UtilityReceipt line={receipt} onClose={() => setReceipt(null)} rate={numericRate} year={year} />}
    </main>
  );
}

function UtilityReceipt({ line, rate, year, onClose }: { line: UtilityLine; rate: number; year: string; onClose: () => void }) { return <div aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-stone-950/40 p-4" role="dialog"><section className="flex max-h-[94vh] w-full max-w-3xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl dark:bg-stone-900"><header className="flex items-start justify-between border-b border-stone-100 p-5 dark:border-stone-800"><div><h2 className="text-lg font-semibold">Recibo de utilidades</h2><p className="mt-1 text-sm text-stone-500">Período anual {year}.</p></div><Button aria-label="Cerrar" onClick={onClose} size="icon-sm" variant="ghost"><X /></Button></header><div className="overflow-y-auto p-5"><article className="mx-auto max-w-2xl border border-stone-200 bg-white p-7 text-stone-900" id="utilities-receipt-print"><div className="flex items-center justify-between border-b border-stone-200 pb-5"><div><h3 className="font-semibold">Distribuidora El Roble, C.A.</h3><p className="mt-1 text-xs text-stone-500">Recibo de utilidades · {year}</p></div><Gift className="text-[#14352d]" /></div><div className="mt-5 grid gap-3 text-sm sm:grid-cols-2"><p><span className="text-stone-500">Trabajador</span><br /><b>{line.employee.name}</b></p><p><span className="text-stone-500">Cédula</span><br /><b>{line.employee.identity}</b></p><p><span className="text-stone-500">Días aplicados</span><br /><b>{line.days} días</b></p><p><span className="text-stone-500">Tasa aplicada</span><br /><b>{money(rate)}</b></p></div><div className="mt-6 flex justify-between border-y border-stone-200 py-4"><span>Utilidades del período</span><b>{money(line.amount)}</b></div><div className="mt-16 grid grid-cols-2 gap-12 text-center text-xs"><div className="border-t border-stone-500 pt-2">Firma autorizada</div><div className="border-t border-stone-500 pt-2">Firma del trabajador</div></div><p className="mt-8 text-[10px] leading-4 text-stone-500">Borrador demostrativo. La base y el prorrateo deben confirmarse antes de su aprobación.</p></article></div><footer className="flex justify-end gap-2 border-t border-stone-100 p-5 dark:border-stone-800"><Button onClick={onClose} variant="outline">Cerrar</Button><Button className="bg-[#14352d] hover:bg-[#0e2821]" onClick={() => window.print()}><FileText /> Imprimir / guardar PDF</Button></footer></section></div>; }
function Field({ children, label }: { children: React.ReactNode; label: string }) { return <label className="text-sm font-medium">{label}{children}</label>; }
function formatDate(value: string) { return new Intl.DateTimeFormat("es-VE", { day: "2-digit", month: "short", year: "numeric", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`)); }
