"use client";

import { AlertTriangle, CalendarCheck2, FileText, Settings2, Umbrella, X } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { employeesDemo, money, type Employee } from "@/lib/employees-demo";

const suggestions = employeesDemo.filter((employee) => ["maria-gonzalez", "carlos-medina"].includes(employee.id));

export function VacationWorkspace() {
  const [rate, setRate] = useState("47,50");
  const [receipt, setReceipt] = useState<Employee | null>(null);
  const [prepared, setPrepared] = useState<string[]>([]);
  const numericRate = Number(rate.replace(",", ".")) || 0;
  return (
    <main className="mx-auto w-full max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
      <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm text-stone-500">Empresa activa / Empleados / Vacaciones</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Vacaciones</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-stone-600 dark:text-stone-300">Anticipa aniversarios, calcula vacaciones y bono vacacional por separado y genera el recibo.</p></div><Link className="inline-flex h-9 items-center gap-2 rounded-lg border border-stone-200 bg-white px-3 text-sm font-medium dark:border-stone-700 dark:bg-stone-900" href="/configuracion/empresa/laboral"><Settings2 size={16} /> Revisar reglas</Link></header>
      <section className="mt-7 grid gap-4 sm:grid-cols-3"><Metric label="Próximos 30 días" value="2 trabajadores" detail="Requieren programación" /><Metric label="Regla de vacaciones" value="15 + antigüedad" detail="Tope configurado · 30 días" /><Metric label="Bono vacacional" value="Regla separada" detail="15 + antigüedad · revisar fuente" /></section>
      <section className="mt-6 rounded-xl border border-stone-200 bg-white p-5 shadow-sm dark:border-stone-800 dark:bg-stone-900"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="font-semibold">Tasa para la simulación</h2><p className="mt-1 text-sm text-stone-500">El recibo se expresará en bolívares y conservará la tasa aplicada.</p></div><label className="w-full text-sm font-medium sm:w-56">Tasa propia · Bs<Input className="field mt-1.5" inputMode="decimal" onChange={(event) => setRate(event.target.value)} value={rate} /></label></div><p className="mt-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs leading-5 text-amber-900 dark:border-amber-900 dark:bg-amber-950/25 dark:text-amber-100"><AlertTriangle className="mr-1 inline" size={14} />Cálculo demostrativo sobre salario vigente. La base, progresividad y fuente deben validarse antes de aprobar.</p></section>
      <section className="mt-6 overflow-hidden rounded-xl border border-stone-200 bg-white shadow-sm dark:border-stone-800 dark:bg-stone-900"><header className="flex items-start gap-3 border-b border-stone-100 p-5 dark:border-stone-800"><span className="grid size-9 place-items-center rounded-lg bg-sky-50 text-sky-700 dark:bg-sky-950"><CalendarCheck2 size={18} /></span><div><h2 className="font-semibold">Próximos a aniversario</h2><p className="mt-1 text-sm text-stone-500">Sugeridos automáticamente desde 30 días antes.</p></div></header><div className="overflow-x-auto"><Table className="min-w-[900px]"><TableHeader className="bg-stone-50 text-xs text-stone-500 dark:bg-stone-900/50"><TableRow><TableHead className="px-5 py-3">Trabajador</TableHead><TableHead className="px-5 py-3">Aniversario</TableHead><TableHead className="px-5 py-3">Antigüedad</TableHead><TableHead className="px-5 py-3">Días de descanso</TableHead><TableHead className="px-5 py-3">Días de bono</TableHead><TableHead className="px-5 py-3">Estimado total</TableHead><TableHead className="px-5 py-3 text-right">Acción</TableHead></TableRow></TableHeader><TableBody>{suggestions.map((employee) => { const years = serviceYears(employee); const days = benefitDays(years); const total = employee.salary / 30 * days * numericRate * 2; const isPrepared = prepared.includes(employee.id); return <TableRow key={employee.id}><TableCell className="px-5 py-4"><b>{employee.name}</b><p className="mt-0.5 text-xs text-stone-500">{employee.identity} · {employee.salary} {employee.salaryCurrency}</p></TableCell><TableCell className="px-5 py-4"><b>{employee.id === "maria-gonzalez" ? "18 ago 2026" : "27 ago 2026"}</b><p className="mt-0.5 text-xs text-sky-700">{employee.id === "maria-gonzalez" ? "18 días" : "27 días"}</p></TableCell><TableCell className="px-5 py-4">{years} años</TableCell><TableCell className="px-5 py-4">{days} días</TableCell><TableCell className="px-5 py-4">{days} días</TableCell><TableCell className="px-5 py-4 font-semibold">{money(total)}</TableCell><TableCell className="px-5 py-4 text-right"><Button onClick={() => { setReceipt(employee); if (!isPrepared) setPrepared((current) => [...current, employee.id]); }} size="sm" variant={isPrepared ? "outline" : "default"} className={isPrepared ? "" : "bg-[#14352d] hover:bg-[#0e2821]"}><FileText /> {isPrepared ? "Ver recibo" : "Calcular"}</Button></TableCell></TableRow>; })}</TableBody></Table></div></section>
      <section className="mt-6 rounded-xl border border-stone-200 bg-white p-5 shadow-sm dark:border-stone-800 dark:bg-stone-900"><div className="flex items-center gap-3"><Umbrella className="text-[#14352d] dark:text-emerald-300" size={19} /><div><h2 className="font-semibold">Programación del disfrute</h2><p className="mt-1 text-sm text-stone-500">La empresa podrá programar la fecha efectiva al aniversario o dentro de una política colectiva de fin de año. El pago y el disfrute quedarán registrados como eventos distintos.</p></div></div></section>
      {receipt && <VacationReceipt employee={receipt} onClose={() => setReceipt(null)} rate={numericRate} />}
    </main>
  );
}

function VacationReceipt({ employee, rate, onClose }: { employee: Employee; rate: number; onClose: () => void }) { const years = serviceYears(employee); const days = benefitDays(years); const vacation = employee.salary / 30 * days * rate; const bonus = employee.salary / 30 * days * rate; return <div aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-stone-950/40 p-4" role="dialog"><section className="flex max-h-[94vh] w-full max-w-3xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl dark:bg-stone-900"><header className="flex items-start justify-between border-b border-stone-100 p-5 dark:border-stone-800"><div><h2 className="text-lg font-semibold">Recibo de vacaciones</h2><p className="mt-1 text-sm text-stone-500">Vacaciones y bono vacacional identificados por separado.</p></div><Button aria-label="Cerrar" onClick={onClose} size="icon-sm" variant="ghost"><X /></Button></header><div className="overflow-y-auto p-5"><article className="mx-auto max-w-2xl border border-stone-200 bg-white p-7 text-stone-900" id="vacation-receipt-print"><div className="flex items-center justify-between border-b border-stone-200 pb-5"><div><h3 className="font-semibold">Distribuidora El Roble, C.A.</h3><p className="mt-1 text-xs text-stone-500">Recibo de vacaciones · 2026</p></div><Umbrella className="text-[#14352d]" /></div><div className="mt-5 grid gap-3 text-sm sm:grid-cols-2"><p><span className="text-stone-500">Trabajador</span><br /><b>{employee.name}</b></p><p><span className="text-stone-500">Cédula</span><br /><b>{employee.identity}</b></p><p><span className="text-stone-500">Antigüedad</span><br /><b>{years} años</b></p><p><span className="text-stone-500">Tasa aplicada</span><br /><b>{money(rate)}</b></p></div><div className="mt-6 overflow-hidden rounded-lg border border-stone-200"><div className="grid grid-cols-[1fr_6rem_9rem] bg-stone-50 px-4 py-2 text-xs font-medium text-stone-500"><span>Concepto</span><span>Días</span><span className="text-right">Monto</span></div><ReceiptRow label="Vacaciones" days={days} amount={vacation} /><ReceiptRow label="Bono vacacional" days={days} amount={bonus} /></div><div className="mt-5 flex justify-between border-t-2 border-stone-900 pt-4"><b>Total a pagar</b><b>{money(vacation + bonus)}</b></div><div className="mt-16 grid grid-cols-2 gap-12 text-center text-xs"><div className="border-t border-stone-500 pt-2">Firma autorizada</div><div className="border-t border-stone-500 pt-2">Firma del trabajador</div></div><p className="mt-8 text-[10px] leading-4 text-stone-500">Documento demostrativo sujeto a validación de reglas, fuente y vigencia.</p></article></div><footer className="flex justify-end gap-2 border-t border-stone-100 p-5 dark:border-stone-800"><Button onClick={onClose} variant="outline">Cerrar</Button><Button className="bg-[#14352d] hover:bg-[#0e2821]" onClick={() => window.print()}><FileText /> Imprimir / guardar PDF</Button></footer></section></div>; }
function ReceiptRow({ label, days, amount }: { label: string; days: number; amount: number }) { return <div className="grid grid-cols-[1fr_6rem_9rem] border-t border-stone-100 px-4 py-3 text-sm"><span>{label}</span><span>{days}</span><span className="text-right">{money(amount)}</span></div>; }
function serviceYears(employee: Employee) { return Math.max(1, 2026 - Number(employee.admissionDate.slice(0, 4))); }
function benefitDays(years: number) { return Math.min(30, 15 + Math.max(0, years - 1)); }
function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className="rounded-xl border border-stone-200 bg-white p-5 shadow-sm dark:border-stone-800 dark:bg-stone-900"><p className="text-xs font-medium uppercase tracking-wide text-stone-400">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p><p className="mt-1 text-xs text-stone-500">{detail}</p></article>; }
